In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
#Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[4,5,6],[7,8,9]])

# Create a 3-dimensional NumPy array using np.array()
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [3]:
a1

array([1, 2, 3])

In [4]:
# a 1-dimensional NumPy array
a1,a1.ndim,a1.shape,a1.size,type(a1),a1.dtype

(array([1, 2, 3]), 1, (3,), 3, numpy.ndarray, dtype('int32'))

In [5]:
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
# a 2-dimensional NumPy array
a2,a2.ndim,a2.shape,a2.size,a2.dtype,type(a2)

(array([[4, 5, 6],
        [7, 8, 9]]),
 2,
 (2, 3),
 6,
 dtype('int32'),
 numpy.ndarray)

In [7]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
# a 3-dimensional NumPy array
a3,a3.ndim,a3.shape,a3.size,a3.dtype,type(a3)

(array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]),
 3,
 (1, 3, 3),
 9,
 dtype('int32'),
 numpy.ndarray)

In [9]:
# Import pandas 
import pandas as pd

# create a DataFrame out of one the arrays you've created
df=pd.DataFrame(a1,index=[0,1,2])
df

0
0  1
1  2
2  3

In [10]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array=np.random.randint(0,10,size=(7,2))
random_array

array([[4, 1],
       [3, 6],
       [1, 5],
       [7, 4],
       [4, 3],
       [8, 9],
       [2, 1]])

In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float=np.random.random((3,5))
random_float

array([[0.20887382, 0.05304888, 0.17705419, 0.64322608, 0.5995298 ],
       [0.32267729, 0.94706138, 0.34862238, 0.352139  , 0.65156458],
       [0.85689519, 0.77809436, 0.1723688 , 0.5844668 , 0.78662768]])

In [15]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array2=np.random.randint(0,10,size=(4,6))
random_array2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [16]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array=np.random.randint(0,10,size=(3,7))
random_array
# Find the unique numbers in the array you just created

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [17]:
# Find the 0'th index of the latest array you created
random_array[0]

array([8, 0, 9, 2, 6, 3, 8])

In [18]:
#Get the first 2 rows of latest array you created
random_array[:2]    

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [19]:
# Get the last 2 rows of latest array you created
random_array[-2:]

array([[2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [20]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2,:2]

array([[8, 0],
       [2, 4]])

In [21]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array3=np.random.randint(0,10,size=(3,5))
ones=np.ones((3,5))

In [22]:
random_array3

array([[4, 1, 3, 6, 7],
       [2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9]])

In [23]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# Add the two arrays together
random_array3+ones

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [25]:
# Create another array of ones of shape (5, 3)
ones=np.ones((5,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# Try add the array of ones and the other most recent array together
random_array3+ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [ ]:
# Create another array of ones of shape (3, 5)
ones=np.ones((3,5))
ones

In [ ]:
random_array3

In [ ]:
# Subtract the new array of ones from the other most recent array
random_array3-ones

In [ ]:
# Multiply the ones array with the latest array
random_array3 * ones

In [ ]:
random_array3

In [ ]:
#Take the latest array to the power of 2 using '**'
random_array3**2

In [ ]:
random_array3

In [ ]:
# Do the same thing with np.square()
np.square(random_array3)

In [ ]:
random_array3

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(random_array3)

In [ ]:
random_array3

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(random_array3)

In [ ]:
random_array3

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(random_array3)

In [ ]:
random_array3

In [ ]:
# Find the standard deviation of the latest array
np.std(random_array3)

In [ ]:
random_array3

In [ ]:
np.var(random_array3)

In [ ]:
random_array3

In [ ]:
random_array3.reshape(3,5,1)

In [ ]:
random_array3

In [ ]:
# Transpose the latest array
random_array3.T

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1=np.random.randint(0,10,size=(3,3))
arr2=np.random.randint(0,10,size=(3,2))

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
# Perform a dot product on the two newest arrays you created
arr1.dot(arr2)

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr1=np.random.randint(0,10,size=(4,3))
arr2=np.random.randint(0,10,size=(4,3))

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
# Perform a dot product on the two newest arrays you created
arr1.dot(arr2)

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
arr1.T.dot(arr2)

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1=np.random.randint(0,10,size=(4,5))
arr2=np.random.randint(0,10,size=(4,5))

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
# Compare the two arrays with '>'
arr1>arr2

In [ ]:
# Compare the two arrays with '>='
arr1>=arr2

In [ ]:
# Find which elements of the first array are greater than 7
arr1[arr1>7]

In [ ]:
# Which parts of each array are equal? (try using '==')
arr1==arr2

In [ ]:
random_array3

In [ ]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array3)

In [ ]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array3)

In [ ]:
random_array3

In [ ]:
 # Find the index with the maximum value in one of the arrays you've created

np.argmax(random_array3)

In [ ]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array3)

In [27]:
random_array

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [28]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_array,axis=1)

array([2, 5, 4], dtype=int64)

In [29]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(random_array,axis=0)

array([0, 1, 0, 1, 2, 1, 2], dtype=int64)

In [31]:
# Create an array of normally distributed random numbers
np.random.randint(100,size=(5,5))

array([[53, 92, 62, 17, 89],
       [43, 33, 73, 61, 99],
       [13, 94, 47, 14, 71],
       [77, 86, 61, 39, 84],
       [79, 81, 52, 23, 25]])

In [32]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])