# importing numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\ABDULLAH\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

# Ndarray: The Heart of the Library
To define a new ndarray, the easiest way is to use the array() function

In [3]:
# one dimensional array
a=np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int32')

In [7]:
# to find dimension ndim function is used
a.ndim

1

In [8]:
# to find array size
a.size

4

In [9]:
a.shape

(4,)

In [10]:
# two dimensional array
two_d=np.array([[1,2,3,4],[5,6,7,8]])

In [11]:
two_d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
two_d.ndim

2

In [13]:
two_d.size

8

In [14]:
two_d.shape

(2, 4)

In [15]:
#size of each item in bytes
two_d.itemsize

4

In [16]:
#data is the buffer containing the actual elements of the array
two_d.data

# Create an Array

In [17]:
# one dimensional array
a=np.array([1,2,3,4])

# two dimensional array
two_d=np.array([[1,2,3,4],[5,6,7,8]])

In [18]:
a

array([1, 2, 3, 4])

In [19]:
two_d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
# three dimensional array
e=np.array([[1,3,5],(4,2,6),[7,8,9]])

In [21]:
e

array([[1, 3, 5],
       [4, 2, 6],
       [7, 8, 9]])

# Types of Data

In [22]:
g=np.array([['a','b','c','d'],['e','f','g','h']])

In [23]:
g

array([['a', 'b', 'c', 'd'],
       ['e', 'f', 'g', 'h']], dtype='<U1')

In [24]:
g.dtype

dtype('<U1')

In [25]:
g.dtype.name

'str32'

# The dtype Option

In [26]:
com=np.array([[1,2,3],[4,5,6]],dtype=complex)

In [27]:
com

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [28]:
fl=np.array([[1,2,3],[4,5,6]],dtype=float)

In [29]:
fl

array([[1., 2., 3.],
       [4., 5., 6.]])

# Intrinsic Creation of an Array

In [30]:
#The zeros() function, for example, creates a full array of zeros with dimensions defined by the shape argument
z=np.zeros((5,5))

In [31]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
z=np.zeros((3,3))

In [33]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
#  ones() function creates an array full of ones
one=np.ones((4,4))

In [35]:
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
one.ndim

2

In [38]:
one.shape

(4, 4)

In [39]:
one.size

16

In [40]:
one.itemsize

8

In [41]:
# arange(). This function generates NumPy arrays with numerical sequences that respond to particular rules depending on the passed arguments
ar=np.arange(0,10)

In [42]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
ar1=np.arange(100,125)
ar1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [44]:
ar2=np.arange(1,100,3)
ar2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [45]:
#  reshape() function. This function dividesa linear array in different parts in the manner specified by the shape argument.
ar_re=np.arange(1,25).reshape(4,6)


In [46]:
ar_re

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [47]:
ar_re2=np.arange(0,30).reshape(10,3)

In [48]:
ar_re2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

#  linspace(). This function still takes as its first two
arguments the initial and end values of the sequence, but the third argument, instead of specifying the
distance between one element and the next, defines the number of elements into which we want the interval
to be split.

In [49]:
arr4=np.linspace(1,10,3)

In [50]:
arr4

array([ 1. ,  5.5, 10. ])

In [51]:
arr5=np.linspace(1,10,5)

In [52]:
arr5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [53]:
arr=np.linspace(1,10,10)

In [54]:
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Random

In [55]:
np.random.random(3)

array([0.02264097, 0.4961672 , 0.54826999])

In [56]:
np.random.rand(3,3)

array([[0.26221286, 0.02947736, 0.42045459],
       [0.47502973, 0.84595555, 0.0299708 ],
       [0.95130659, 0.62320449, 0.10145021]])

# Arithmetic operation

In [57]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [58]:
a+4

array([4, 5, 6, 7])

In [59]:
a/4

array([0.  , 0.25, 0.5 , 0.75])

In [60]:
a*4

array([ 0,  4,  8, 12])

In [61]:
a-4

array([-4, -3, -2, -1])

In [62]:
a

array([0, 1, 2, 3])

In [63]:
b=np.arange(4,8)

In [64]:
b

array([4, 5, 6, 7])

In [65]:
a+b

array([ 4,  6,  8, 10])

In [66]:
a-b

array([-4, -4, -4, -4])

In [67]:
b-a

array([4, 4, 4, 4])

In [68]:
a/b

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [69]:
a*b

array([ 0,  5, 12, 21])

In [70]:
a*np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [71]:
a*sqrt(b)

NameError: name 'sqrt' is not defined

In [72]:
a*np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [73]:
A=np.arange(9).reshape((3,3))

In [74]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
B=np.ones((3,3))

In [76]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
A+B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [78]:
A*B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

# The Matrix Product
dot() function

In [79]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [80]:
dot(A,B)

NameError: name 'dot' is not defined

In [81]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [82]:
B.dot(A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [83]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

# Increment and Decrement Operators

In [84]:
a

array([0, 1, 2, 3])

In [85]:
a+=1

In [86]:
a

array([1, 2, 3, 4])

In [87]:
a-=1

In [88]:
a

array([0, 1, 2, 3])

In [89]:
a+=5

In [90]:
a

array([5, 6, 7, 8])

In [91]:
a*=6

In [92]:
a

array([30, 36, 42, 48])

# Universal Functions (ufunc)

In [93]:
a

array([30, 36, 42, 48])

In [94]:
a.np.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [95]:
np.sqrt(a)

array([5.47722558, 6.        , 6.4807407 , 6.92820323])

In [96]:
np.log(a)

array([3.40119738, 3.58351894, 3.73766962, 3.87120101])

In [97]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
np.log(A)

C:\Users\ABDULLAH\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154]])

In [99]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [100]:
np.sin(B)

array([[0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098]])

# Aggregate Functions

In [101]:
a

array([30, 36, 42, 48])

In [102]:
a.sum()

156

In [103]:
a.min()

30

In [104]:
a.max()

48

In [105]:
a.std()

6.708203932499369

In [106]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
A.sum()

36

In [108]:
A.min()

0

In [109]:
A.max()

8

In [110]:
A.std()

2.581988897471611

# Indexing, Slicing, and Iterating

# indexing

In [111]:
a

array([30, 36, 42, 48])

In [112]:
a[2]

42

In [113]:
a[-1]

48

In [114]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
A[0,2]

2

In [116]:
A[2,1]

7

In [117]:
A[-1,-3]

6

In [118]:
A[-1,-1]

8

In [119]:
A[-3,-2]

1

# Slicing

In [120]:
c=np.random.randint(10,20,size=(3,5))

In [121]:
c

array([[15, 12, 10, 16, 13],
       [10, 16, 12, 13, 13],
       [12, 13, 19, 15, 12]])

In [122]:
c[0:2]

array([[15, 12, 10, 16, 13],
       [10, 16, 12, 13, 13]])

In [123]:
c[0,:2]

array([15, 12])

In [124]:
c[:,:2]

array([[15, 12],
       [10, 16],
       [12, 13]])

In [125]:
c[:1,:1]

array([[15]])

In [126]:
c[:2,:3]

array([[15, 12, 10],
       [10, 16, 12]])

In [127]:
c[:3,:2]

array([[15, 12],
       [10, 16],
       [12, 13]])

In [128]:
a

array([30, 36, 42, 48])

In [129]:
a[2:4]

array([42, 48])

In [130]:
a[:1]

array([30])

In [131]:
a[:-1]

array([30, 36, 42])

In [132]:
a[-1:]

array([48])

In [133]:
a[1:3:2]

array([36])

In [134]:
a[::2]

array([30, 42])

In [135]:
a[::3]

array([30, 48])

# Iterating an Array

In [136]:
for i in a:
    print (i)

30
36
42
48


In [137]:
for i in A:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [138]:
for i in A.flat:
    print(i)

0
1
2
3
4
5
6
7
8


In [139]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [140]:
np.apply_along_axis(np.mean,axis=0,arr=A)

array([3., 4., 5.])

In [141]:
np.apply_along_axis(np.sum,axis=1,arr=A)

array([ 3, 12, 21])

In [142]:
def foo(x):
    return x/2

In [143]:
np.apply_along_axis(foo,axis=0,arr=A)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [144]:
np.apply_along_axis(foo,axis=1,arr=A)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

 # Conditions and Boolean Arrays

In [145]:
A=np.random.random((4,4))

In [146]:
A

array([[0.01988365, 0.73453816, 0.57270646, 0.37920389],
       [0.38758971, 0.34008442, 0.69228008, 0.39720243],
       [0.48733348, 0.00438886, 0.20949545, 0.51009305],
       [0.7717864 , 0.07068849, 0.06660227, 0.49589171]])

In [147]:
A<0.5

array([[ True, False, False,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False],
       [False,  True,  True,  True]])

In [148]:
A[0.5]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [149]:
A[A<0.5]

array([0.01988365, 0.37920389, 0.38758971, 0.34008442, 0.39720243,
       0.48733348, 0.00438886, 0.20949545, 0.07068849, 0.06660227,
       0.49589171])

# Shape Manipulation

In [150]:
c=np.random.rand(18)

In [151]:
c

array([0.46581337, 0.09659364, 0.09285092, 0.98612979, 0.03360329,
       0.89974511, 0.82100794, 0.18906268, 0.72532365, 0.11445736,
       0.65149555, 0.65445485, 0.97730924, 0.26203449, 0.07516028,
       0.40917752, 0.16216471, 0.86383271])

In [152]:
c=c.reshape(2,9)

In [153]:
c

array([[0.46581337, 0.09659364, 0.09285092, 0.98612979, 0.03360329,
        0.89974511, 0.82100794, 0.18906268, 0.72532365],
       [0.11445736, 0.65149555, 0.65445485, 0.97730924, 0.26203449,
        0.07516028, 0.40917752, 0.16216471, 0.86383271]])

In [154]:
c.shape

(2, 9)

In [155]:
d=np.random.random(15)

In [156]:
d.shape

(15,)

In [157]:
d

array([0.90898153, 0.97535655, 0.72817673, 0.92244488, 0.75765579,
       0.0428665 , 0.04407088, 0.88797385, 0.86925465, 0.53098597,
       0.26354144, 0.08750676, 0.77826928, 0.58515736, 0.29702012])

In [158]:
d=d.reshape(5,3)

In [159]:
d.shape

(5, 3)

In [160]:
d.shape=(3,5)

In [161]:
d

array([[0.90898153, 0.97535655, 0.72817673, 0.92244488, 0.75765579],
       [0.0428665 , 0.04407088, 0.88797385, 0.86925465, 0.53098597],
       [0.26354144, 0.08750676, 0.77826928, 0.58515736, 0.29702012]])

In [162]:
d.shape

(3, 5)

# ravel() function convert two dimensional array into one dimension

In [163]:
d=d.ravel()

In [164]:
d

array([0.90898153, 0.97535655, 0.72817673, 0.92244488, 0.75765579,
       0.0428665 , 0.04407088, 0.88797385, 0.86925465, 0.53098597,
       0.26354144, 0.08750676, 0.77826928, 0.58515736, 0.29702012])

In [165]:
d.shape

(15,)

In [166]:
c

array([[0.46581337, 0.09659364, 0.09285092, 0.98612979, 0.03360329,
        0.89974511, 0.82100794, 0.18906268, 0.72532365],
       [0.11445736, 0.65149555, 0.65445485, 0.97730924, 0.26203449,
        0.07516028, 0.40917752, 0.16216471, 0.86383271]])

In [167]:
c.shape

(2, 9)

In [168]:
c=c.ravel()

In [169]:
c

array([0.46581337, 0.09659364, 0.09285092, 0.98612979, 0.03360329,
       0.89974511, 0.82100794, 0.18906268, 0.72532365, 0.11445736,
       0.65149555, 0.65445485, 0.97730924, 0.26203449, 0.07516028,
       0.40917752, 0.16216471, 0.86383271])

In [170]:
c.shape

(18,)

In [171]:
a

array([30, 36, 42, 48])

In [172]:
a.transpose()

array([30, 36, 42, 48])

In [173]:
c

array([0.46581337, 0.09659364, 0.09285092, 0.98612979, 0.03360329,
       0.89974511, 0.82100794, 0.18906268, 0.72532365, 0.11445736,
       0.65149555, 0.65445485, 0.97730924, 0.26203449, 0.07516028,
       0.40917752, 0.16216471, 0.86383271])

In [174]:
c.transpose()

array([0.46581337, 0.09659364, 0.09285092, 0.98612979, 0.03360329,
       0.89974511, 0.82100794, 0.18906268, 0.72532365, 0.11445736,
       0.65149555, 0.65445485, 0.97730924, 0.26203449, 0.07516028,
       0.40917752, 0.16216471, 0.86383271])

In [175]:
A

array([[0.01988365, 0.73453816, 0.57270646, 0.37920389],
       [0.38758971, 0.34008442, 0.69228008, 0.39720243],
       [0.48733348, 0.00438886, 0.20949545, 0.51009305],
       [0.7717864 , 0.07068849, 0.06660227, 0.49589171]])

In [176]:
A.transpose()

array([[0.01988365, 0.38758971, 0.48733348, 0.7717864 ],
       [0.73453816, 0.34008442, 0.00438886, 0.07068849],
       [0.57270646, 0.69228008, 0.20949545, 0.06660227],
       [0.37920389, 0.39720243, 0.51009305, 0.49589171]])

In [177]:
A.shape

(4, 4)

# Array Manipulation

# Joining Arrays

In [178]:
a_1=np.ones((3,3))

In [179]:
a_1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [180]:
a_0=np.zeros((3,3))

In [181]:
a_0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [182]:
np.vstack((a_1,a_0))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [183]:
np.hstack((a_1,a_0))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [184]:
a

array([30, 36, 42, 48])

In [185]:
b

array([4, 5, 6, 7])

In [186]:
c=np.array([0,9,1,20])

In [187]:
c

array([ 0,  9,  1, 20])

In [188]:
np.column_stack((a,b,c))

array([[30,  4,  0],
       [36,  5,  9],
       [42,  6,  1],
       [48,  7, 20]])

In [189]:
np.column_stack((c,a,b))

array([[ 0, 30,  4],
       [ 9, 36,  5],
       [ 1, 42,  6],
       [20, 48,  7]])

In [190]:
np.row_stack((a,b,c))

array([[30, 36, 42, 48],
       [ 4,  5,  6,  7],
       [ 0,  9,  1, 20]])

In [191]:
A

array([[0.01988365, 0.73453816, 0.57270646, 0.37920389],
       [0.38758971, 0.34008442, 0.69228008, 0.39720243],
       [0.48733348, 0.00438886, 0.20949545, 0.51009305],
       [0.7717864 , 0.07068849, 0.06660227, 0.49589171]])

In [192]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [193]:
np.hsplit(B,3)

[array([[1.],
        [1.],
        [1.]]),
 array([[1.],
        [1.],
        [1.]]),
 array([[1.],
        [1.],
        [1.]])]

In [194]:
c

array([ 0,  9,  1, 20])

In [195]:
np.hsplit(c,4)

[array([0]), array([9]), array([1]), array([20])]

In [196]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [197]:
np.vsplit(B,3)

[array([[1., 1., 1.]]), array([[1., 1., 1.]]), array([[1., 1., 1.]])]

In [198]:
A=np.arange(16).reshape(8,2)

In [199]:
A

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [200]:
np.vsplit(A,4)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[ 8,  9],
        [10, 11]]),
 array([[12, 13],
        [14, 15]])]

In [201]:
np.hsplit(A,2)

[array([[ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12],
        [14]]),
 array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15]])]

In [202]:
A.shape=(4,4)

In [203]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [204]:
[a1,a2,a3,a4]=np.split(A,4)

In [205]:
a1

array([[0, 1, 2, 3]])

In [206]:
a2

array([[4, 5, 6, 7]])

In [207]:
a3

array([[ 8,  9, 10, 11]])

In [208]:
a4

array([[12, 13, 14, 15]])

In [209]:
[b1,b2,b3,b4]=np.split(A,4,axis=1)

In [210]:
b1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [211]:
b2

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [212]:
b3

array([[ 2],
       [ 6],
       [10],
       [14]])

In [213]:
b4

array([[ 3],
       [ 7],
       [11],
       [15]])

# Copies or Views of Objects

In [214]:
a

array([30, 36, 42, 48])

In [215]:
b=a

In [216]:
b

array([30, 36, 42, 48])

In [217]:
a[2]=0

In [218]:
# here b  change after changing the value of a .so it is not a copy
b

array([30, 36,  0, 48])

In [219]:
c=a[0:2]

In [220]:
c

array([30, 36])

In [223]:
a[0]=0

In [224]:
c

array([ 0, 36])

In [225]:
a

array([ 0, 36,  0, 48])

In [226]:
b

array([ 0, 36,  0, 48])

In [227]:
c

array([ 0, 36])

In [229]:
# to completely copy of an array need to use copy function
d=np.copy(a)

In [230]:
d

array([ 0, 36,  0, 48])

In [231]:
a[0]=1

In [232]:
a

array([ 1, 36,  0, 48])

In [234]:
# here the value of d is not change after changing the value of a 
d

array([ 0, 36,  0, 48])

# Broadcasting the length of each dimension must be equal between the two arrays or one of them must be equal to 1

In [235]:
A=np.random.randint(16,size=(4,4))

In [236]:
A

array([[12,  2,  6, 13],
       [15,  3, 11,  2],
       [ 1,  9,  0,  3],
       [ 0, 15, 10,  1]])

In [237]:
B=np.arange(4)

In [238]:
B

array([0, 1, 2, 3])

In [239]:
A*B

array([[ 0,  2, 12, 39],
       [ 0,  3, 22,  6],
       [ 0,  9,  0,  9],
       [ 0, 15, 20,  3]])

In [240]:
A.dot(B)

array([53, 31, 18, 38])

In [241]:
A+B

array([[12,  3,  8, 16],
       [15,  4, 13,  5],
       [ 1, 10,  2,  6],
       [ 0, 16, 12,  4]])

In [246]:
m=np.arange(6).reshape(3,1,2)

In [247]:
m

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [244]:
n=np.arange(6).reshape(3,2,1)

In [245]:
n

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [248]:
m*n

array([[[ 0,  0],
        [ 0,  1]],

       [[ 4,  6],
        [ 6,  9]],

       [[16, 20],
        [20, 25]]])

In [249]:
m.dot(n)

array([[[[ 1],
         [ 3],
         [ 5]]],


       [[[ 3],
         [13],
         [23]]],


       [[[ 5],
         [23],
         [41]]]])

# Structured Arrays
much more complex not only in size but also in the structure itself

In [253]:
structured=np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3, 2-2j),(3, 'Third', 0.8, 1+3j)],dtype=('i2, a6, f4, c8'))

In [254]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [256]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3,2-2j),
(3, 'Third', 0.8, 1+3j)],dtype=('int16, a6, float32, complex64'))

In [257]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [258]:
structured[1]

(2, b'Second', 1.3, 2.-2.j)

In [259]:
structures['f1']

NameError: name 'structures' is not defined

# Reading and Writing Array Data on Files

# Loading and Saving Data in Binary Files

In [263]:
data=np.random.random(1000)

In [264]:
data

array([6.46467064e-01, 2.65203460e-01, 7.16377066e-01, 5.11628117e-01,
       3.41220681e-01, 9.20487599e-02, 8.52829191e-01, 1.87686787e-01,
       7.84731172e-02, 4.37049546e-02, 7.02145893e-01, 3.89957892e-01,
       8.35167704e-01, 9.18257076e-02, 8.45640335e-01, 9.22322744e-01,
       4.13464288e-01, 8.90076616e-01, 3.27774460e-01, 7.36457365e-01,
       8.85943851e-01, 7.52267039e-01, 2.30939394e-01, 3.81549491e-01,
       8.52925077e-02, 2.46131386e-01, 1.28764519e-01, 9.39633664e-02,
       2.94960718e-01, 4.71602766e-01, 7.60033092e-01, 8.41274065e-01,
       8.15401162e-01, 8.98873511e-01, 8.51431618e-01, 6.60338481e-01,
       6.86502855e-01, 6.96178563e-01, 8.15168306e-01, 6.88329192e-01,
       2.75499604e-01, 9.60313588e-01, 6.46752776e-01, 7.19220043e-01,
       9.17865237e-01, 7.39321756e-01, 7.89576729e-01, 1.02165719e-01,
       4.00940157e-01, 1.79943059e-01, 1.65461255e-01, 9.99630207e-01,
       4.74876021e-01, 3.46734587e-01, 2.96707644e-01, 8.36889042e-01,
      

In [265]:
# saving data by using save() function
np.save('random_data',data)

In [266]:
# reading data by using load() function and .npy extension
loaded_data=np.load('random_data.npy')

In [267]:
loaded_data

array([6.46467064e-01, 2.65203460e-01, 7.16377066e-01, 5.11628117e-01,
       3.41220681e-01, 9.20487599e-02, 8.52829191e-01, 1.87686787e-01,
       7.84731172e-02, 4.37049546e-02, 7.02145893e-01, 3.89957892e-01,
       8.35167704e-01, 9.18257076e-02, 8.45640335e-01, 9.22322744e-01,
       4.13464288e-01, 8.90076616e-01, 3.27774460e-01, 7.36457365e-01,
       8.85943851e-01, 7.52267039e-01, 2.30939394e-01, 3.81549491e-01,
       8.52925077e-02, 2.46131386e-01, 1.28764519e-01, 9.39633664e-02,
       2.94960718e-01, 4.71602766e-01, 7.60033092e-01, 8.41274065e-01,
       8.15401162e-01, 8.98873511e-01, 8.51431618e-01, 6.60338481e-01,
       6.86502855e-01, 6.96178563e-01, 8.15168306e-01, 6.88329192e-01,
       2.75499604e-01, 9.60313588e-01, 6.46752776e-01, 7.19220043e-01,
       9.17865237e-01, 7.39321756e-01, 7.89576729e-01, 1.02165719e-01,
       4.00940157e-01, 1.79943059e-01, 1.65461255e-01, 9.99630207e-01,
       4.74876021e-01, 3.46734587e-01, 2.96707644e-01, 8.36889042e-01,
      

# Reading File with Tabular Data

In [274]:
data_txt=np.genfromtxt('car_sales.csv',delimiter=' ',names=True)

In [275]:
data_txt

array([(nan, nan), (nan, nan), (nan, nan), (nan, nan), (nan, nan),
       (nan, nan), (nan, nan), (nan, nan), (nan, nan), (nan, nan)],
      dtype=[('MakeColourOdometer', '<f8'), ('KMDoorsPrice', '<f8')])