In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv('Sat_result.csv')
df

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [10]:
model=linear_model.LinearRegression()
model.fit(df[['SAT']],df.GPA)

LinearRegression()

In [11]:
model.coef_

array([0.00165569])

In [12]:
model.intercept_

0.2750402996602803

In [14]:
model.predict([[1775]])

array([3.21388659])

# Saving a model using pickle

In [16]:
import pickle

In [17]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

## Loading a saved_model

In [18]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)

## Predict a value using loaded model

In [19]:
mp.predict([[1775]])

array([3.21388659])

# Saving a model using sklearn Joblib

In [24]:
import joblib

In [25]:

joblib.dump(model,'model_joblib')

['model_joblib']

## Loading the model

In [27]:
m_j=joblib.load('model_joblib')

In [28]:
m_j

LinearRegression()

In [29]:
m_j.predict([[1775]])

array([3.21388659])