In [1]:
from sklearn import svm,datasets
df=datasets.load_iris()

In [2]:
dir(df)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df1=pd.DataFrame(df.data,columns=df.feature_names)

In [5]:
df1

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(df.data,df.target,test_size=0.2)


In [8]:
x_train

array([[5.1, 3.8, 1.9, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [5. , 3.5, 1.3, 0.3],
       [5.8, 2.7, 3.9, 1.2],
       [6.2, 2.8, 4.8, 1.8],
       [5.6, 2.8, 4.9, 2. ],
       [5.8, 2.7, 5.1, 1.9],
       [6.6, 3. , 4.4, 1.4],
       [4.6, 3.1, 1.5, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [7.2, 3.2, 6. , 1.8],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.3, 2.9, 6.3, 1.8],
       [6.1, 3. , 4.6, 1.4],
       [5.1, 2.5, 3. , 1.1],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.5, 4. , 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.4, 3. , 4.5, 1.5],
       [5.8, 2.7, 5.1, 1.9],
       [6.9, 3.1, 5.1, 2.3],
       [5. , 2. , 3.5, 1. ],
       [4.8, 3.4, 1.6, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [5.2, 3.4, 1.4, 0.2],
       [6.8, 3. , 5.5, 2.1],
       [4.8, 3. , 1.4, 0.3],
       [6. , 2.2, 4. , 1. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.5, 3

In [9]:
x_test

array([[5. , 3.3, 1.4, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 2.7, 4.2, 1.3],
       [4.8, 3.1, 1.6, 0.2],
       [5.9, 3. , 4.2, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 2.5, 3.9, 1.1],
       [5.1, 3.8, 1.6, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [5.8, 2.6, 4. , 1.2],
       [5.7, 2.8, 4.1, 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [6.1, 2.6, 5.6, 1.4],
       [6. , 3. , 4.8, 1.8],
       [5.1, 3.4, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5.5, 2.3, 4. , 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3. , 5. , 1.7],
       [6.5, 3. , 5.8, 2.2],
       [6.5, 3.2, 5.1, 2. ],
       [6.7, 3.3, 5.7, 2.5],
       [5.7, 2.8, 4.5, 1.3],
       [5.5, 4.2, 1.4, 0.2],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 3.2, 4.5, 1.5]])

In [10]:
model=svm.SVC(kernel='rbf',C=30,gamma='auto')

In [11]:
model.fit(x_train,y_train)

SVC(C=30, gamma='auto')

In [12]:
model.score(x_test,y_test)

0.9666666666666667

In [13]:
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),df.data,df.target,cv=5)


array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [14]:
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),df.data,df.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [15]:
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),df.data,df.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [16]:
import numpy as np
kernels=['linear','rbf']
c=[1,10,20,30]
avg_scores={}
for k in kernels:
    for i in c:
        scores=cross_val_score(svm.SVC(kernel=k,C=i,gamma='auto'),df.data,df.target,cv=5)
        avg_scores[k +'_'+str(i)]=np.average(scores)
avg_scores

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'linear_30': 0.96,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'rbf_30': 0.96}

In [17]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)
clf.fit(df.data,df.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [18]:
clf.cv_results_

{'mean_fit_time': array([0.00217013, 0.00160031, 0.00119996, 0.00119963, 0.00159888,
        0.00312557]),
 'std_fit_time': array([0.00092203, 0.00049118, 0.00039971, 0.00040023, 0.0010192 ,
        0.00625114]),
 'mean_score_time': array([0.00159817, 0.00060105, 0.00079875, 0.00039964, 0.00099201,
        0.        ]),
 'std_score_time': array([0.00079998, 0.00049078, 0.00039938, 0.00048945, 0.00062027,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [20]:
df2=pd.DataFrame(clf.cv_results_)

In [21]:
df2

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.002170      0.000922         0.001598        0.000800       1   
1       0.001600      0.000491         0.000601        0.000491       1   
2       0.001200      0.000400         0.000799        0.000399      10   
3       0.001200      0.000400         0.000400        0.000489      10   
4       0.001599      0.001019         0.000992        0.000620      20   
5       0.003126      0.006251         0.000000        0.000000      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [22]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits

In [26]:
clf.best_score_

0.9800000000000001

In [28]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [31]:
from sklearn.model_selection import RandomizedSearchCV

In [32]:
rs=RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False,n_iter=2)
rs.fit(df.data,df.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [34]:
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf             0.98
1       1       linear             0.98

In [35]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [40]:
model_params={
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
       'kernel':['rbf','linear']
        }
        
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
          'n_estimators':[1,5,10]
        }
        
    },
    
    'logistic_regression':{
        'model':LogisticRegression( solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
        
    }
    
    
}

In [42]:
scores=[]
for model_names , mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(df.data,df.target)
    scores.append({
        'model':model_names,
        'best_scores':clf.best_score_,
        'best_params':clf.best_params_
    })
    

In [43]:
df3=pd.DataFrame(scores,columns=['model','best_scores','best_params'])
df3

model  best_scores                best_params
0                  svm     0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest     0.960000       {'n_estimators': 10}
2  logistic_regression     0.966667                   {'C': 5}

In [44]:
digits=datasets.load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [45]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [46]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB


In [56]:
model_params={
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
       'kernel':['rbf','linear']
        }
        
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
          'n_estimators':[1,5,10]
        }
        
    },
    
    'logistic_regression':{
        'model':LogisticRegression( solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
        
    },
    'decision_tree':{
        'model':DecisionTreeClassifier(),
        'params':{
           'criterion':['gini','entropy']
        }
    },
        'guassian_nb':{
        'model':GaussianNB(),
        'params':{}
        
},
   'multinomial_nb':{
        'model':MultinomialNB(),
        'params':{} 
    
}
}

In [57]:
scores=[]
for model_names , mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(df.data,df.target)
    scores.append({
        'model':model_names,
        'best_scores':clf.best_score_,
        'best_params':clf.best_params_
    })

In [58]:
df4=pd.DataFrame(scores,columns=['model','best_scores','best_params'])
df4

model  best_scores                best_params
0                  svm     0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest     0.953333        {'n_estimators': 1}
2  logistic_regression     0.966667                   {'C': 5}
3        decision_tree     0.966667      {'criterion': 'gini'}
4          guassian_nb     0.953333                         {}
5       multinomial_nb     0.953333                         {}