# Merging

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
frame1 = pd.DataFrame({'id':['ball','pen','pencil','mug','ashtray'],'price':[1,2,3,4,5]})

In [4]:
frame1

id  price
0     ball      1
1      pen      2
2   pencil      3
3      mug      4
4  ashtray      5

In [5]:
frame2 = pd.DataFrame({'id':['pencil','pencil','ball','pen'],'colors':['white','red','black','blue']})

In [6]:
frame2

id colors
0  pencil  white
1  pencil    red
2    ball  black
3     pen   blue

In [7]:
frame1.merge(frame2)

id  price colors
0    ball      1  black
1     pen      2   blue
2  pencil      3  white
3  pencil      3    red

In [9]:
pd.merge(frame1,frame2)

id  price colors
0    ball      1  black
1     pen      2   blue
2  pencil      3  white
3  pencil      3    red

In [11]:
frame1 = pd.DataFrame({'id':['ball','pencil','pen','mug','ashtray'],'color': ['white','red','red','black','green'],'brand': ['OMG','ABC','ABC','POD','POD']})

In [12]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [13]:
 frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],'brand': ['OMG','POD','ABC','POD']})

In [14]:
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [15]:
frame1.merge(frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [16]:
pd.merge(frame1,frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [18]:
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [19]:
pd.merge(frame1,frame2,on = 'brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [25]:
pd.merge(frame1,frame2,left_on ='id',right_on ='sid')

Empty DataFrame
Columns: [id, color, brand_x, brand_y, sid]
Index: []

In [26]:
 pd.merge(frame1, frame2, left_on='id', right_on='sid')

Empty DataFrame
Columns: [id, color, brand_x, brand_y, sid]
Index: []

In [27]:
pd.merge(frame1,frame2,on='id')

KeyError: 'id'

In [28]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [31]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],'brand': ['OMG','POD','ABC','POD']})

In [35]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [32]:
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [33]:
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

# Full outer join
join all the  columns

In [34]:
pd.merge(frame1,frame2,on='id',how ='outer')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

# left-outer join
jooin all the columns of the left table and corresponding column on the right table

In [36]:
pd.merge(frame1,frame2,on='id',how ='left')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

# Right-outer join
jooin all the columns of the right table and corresponding column on the left table

In [37]:
pd.merge(frame1,frame2,on='id',how = 'right')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

# merging of multiple keys

In [38]:
pd.merge(frame1,frame2,on = ['id','brand'],how ='outer')

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD
5   pencil    NaN   OMG
6   pencil    NaN   POD
7     ball    NaN   ABC
8      pen    NaN   POD

# Merging on Index

In [39]:
pd.merge(frame1,frame2,left_index = True, right_index = True)

id_x  color brand_x    id_y brand_y
0    ball  white     OMG  pencil     OMG
1  pencil    red     ABC  pencil     POD
2     pen    red     ABC    ball     ABC
3     mug  black     POD     pen     POD

In [40]:
frame1.join(frame2)

ValueError: columns overlap but no suffix specified: Index(['id', 'brand'], dtype='object')

In [41]:
frame2.columns= ['brand2','id2']

In [42]:
frame2

brand2  id2
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [43]:
frame1.join(frame2)

id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3      mug  black   POD     pen  POD
4  ashtray  green   POD     NaN  NaN

# Concatenating

In [57]:
array1=np.arange(9).reshape(3,3)

In [46]:
 array2 = np.arange(9).reshape((3,3))+6

In [58]:
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [52]:
array1.concatenate(array2)

AttributeError: 'numpy.ndarray' object has no attribute 'concatenate'

In [53]:
np.concatenate([array1,array2])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [55]:
np.concatenate([array1,array2],axis =1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [56]:
np.concatenate([array1,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [65]:
ser1=pd.Series(np.random.rand(4),index=[1,2,3,4])

In [66]:
ser1

1    0.116105
2    0.327488
3    0.695556
4    0.389839
dtype: float64

In [71]:
ser2 = pd.Series(np.arange(5),index=[5,6,7,8,9])

In [72]:
ser2

5    0
6    1
7    2
8    3
9    4
dtype: int32

In [73]:
ser1.concat(ser2)

AttributeError: 'Series' object has no attribute 'concat'

In [75]:
pd.concat([ser1,ser2])

1    0.116105
2    0.327488
3    0.695556
4    0.389839
5    0.000000
6    1.000000
7    2.000000
8    3.000000
9    4.000000
dtype: float64

In [76]:
pd.concat([ser2,ser1])

5    0.000000
6    1.000000
7    2.000000
8    3.000000
9    4.000000
1    0.116105
2    0.327488
3    0.695556
4    0.389839
dtype: float64

In [77]:
pd.concat([ser1,ser2],axis =1)

0    1
1  0.116105  NaN
2  0.327488  NaN
3  0.695556  NaN
4  0.389839  NaN
5       NaN  0.0
6       NaN  1.0
7       NaN  2.0
8       NaN  3.0
9       NaN  4.0

In [78]:
pd.concat([ser1,ser2],axis=1,join='inner')

Empty DataFrame
Columns: [0, 1]
Index: []

In [80]:
pd.concat([ser1,ser2],keys=[1,2])

1  1    0.116105
   2    0.327488
   3    0.695556
   4    0.389839
2  5    0.000000
   6    1.000000
   7    2.000000
   8    3.000000
   9    4.000000
dtype: float64

In [81]:
pd.concat([ser1,ser2],axis=1,keys=[1,2])

1    2
1  0.116105  NaN
2  0.327488  NaN
3  0.695556  NaN
4  0.389839  NaN
5       NaN  0.0
6       NaN  1.0
7       NaN  2.0
8       NaN  3.0
9       NaN  4.0

In [82]:
 frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[1,2,3],
columns=['A','B','C'])


In [83]:
frame1

A         B         C
1  0.571524  0.317604  0.401364
2  0.090463  0.894649  0.417128
3  0.253627  0.178127  0.628971

In [84]:
 frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[4,5,6],
columns=['A','B','C'])

In [85]:
frame2

A         B         C
4  0.242074  0.109567  0.021115
5  0.133333  0.652231  0.705662
6  0.783844  0.667525  0.206754

In [86]:
pd.concat([frame1,frame2])

A         B         C
1  0.571524  0.317604  0.401364
2  0.090463  0.894649  0.417128
3  0.253627  0.178127  0.628971
4  0.242074  0.109567  0.021115
5  0.133333  0.652231  0.705662
6  0.783844  0.667525  0.206754

In [87]:
pd.concat([frame1,frame2],axis=1)

A         B         C         A         B         C
1  0.571524  0.317604  0.401364       NaN       NaN       NaN
2  0.090463  0.894649  0.417128       NaN       NaN       NaN
3  0.253627  0.178127  0.628971       NaN       NaN       NaN
4       NaN       NaN       NaN  0.242074  0.109567  0.021115
5       NaN       NaN       NaN  0.133333  0.652231  0.705662
6       NaN       NaN       NaN  0.783844  0.667525  0.206754

# Combining

In [88]:
 ser1 = pd.Series(np.random.rand(5),index=[1,2,3,4,5])

In [89]:
ser1

1    0.295207
2    0.851509
3    0.913919
4    0.455926
5    0.021763
dtype: float64

In [90]:
ser2 = pd.Series(np.random.rand(4),index=[2,4,5,6])

In [91]:
ser2

2    0.372628
4    0.327792
5    0.567547
6    0.328563
dtype: float64

In [92]:
ser1.combine_first(ser2)

1    0.295207
2    0.851509
3    0.913919
4    0.455926
5    0.021763
6    0.328563
dtype: float64

# Pivoting

In [5]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),index=['white','red','blue'],columns=['ball','pen','pencil'])

In [6]:
frame

ball  pen  pencil
white     0    1       2
red       3    4       5
blue      6    7       8

In [10]:
frame.stack()

white  ball      0
       pen       1
       pencil    2
red    ball      3
       pen       4
       pencil    5
blue   ball      6
       pen       7
       pencil    8
dtype: int32

In [11]:
frame.unstack()

ball    white    0
        red      3
        blue     6
pen     white    1
        red      4
        blue     7
pencil  white    2
        red      5
        blue     8
dtype: int32

In [12]:
frame.stack()

white  ball      0
       pen       1
       pencil    2
red    ball      3
       pen       4
       pencil    5
blue   ball      6
       pen       7
       pencil    8
dtype: int32

In [13]:
frame.unstack()

ball    white    0
        red      3
        blue     6
pen     white    1
        red      4
        blue     7
pencil  white    2
        red      5
        blue     8
dtype: int32

In [15]:
frame.unstack(0)

ball    white    0
        red      3
        blue     6
pen     white    1
        red      4
        blue     7
pencil  white    2
        red      5
        blue     8
dtype: int32

In [16]:
longframe = pd.DataFrame({ 'color':['white','white','white', 'red','red','red','black','black','black'],'item':['ball','pen','mug','ball','pen','mug','ball','pen','mug'],'value': np.random.rand(9)})

In [17]:
longframe

color  item     value
0  white  ball  0.525271
1  white   pen  0.649640
2  white   mug  0.159301
3    red  ball  0.947592
4    red   pen  0.064643
5    red   mug  0.597839
6  black  ball  0.093969
7  black   pen  0.914146
8  black   mug  0.315524

In [19]:
longframe.stack()

0  color        white
   item          ball
   value     0.525271
1  color        white
   item           pen
   value      0.64964
2  color        white
   item           mug
   value     0.159301
3  color          red
   item          ball
   value     0.947592
4  color          red
   item           pen
   value    0.0646433
5  color          red
   item           mug
   value     0.597839
6  color        black
   item          ball
   value    0.0939691
7  color        black
   item           pen
   value     0.914146
8  color        black
   item           mug
   value     0.315524
dtype: object

In [20]:
wideframe=longframe.pivot('color','item')

In [21]:
wideframe

value                    
item       ball       mug       pen
color                              
black  0.093969  0.315524  0.914146
red    0.947592  0.597839  0.064643
white  0.525271  0.159301  0.649640

# removing

In [22]:
frame1=pd.DataFrame(np.arange(9).reshape(3,3),index=['white','red','green'],columns=['ball','pen','pencil'])

In [23]:
frame1

ball  pen  pencil
white     0    1       2
red       3    4       5
green     6    7       8

# removing column

In [26]:
del frame1['pen']

In [27]:
frame1

ball  pencil
white     0       2
red       3       5
green     6       8

# removing raw

In [30]:
frame1.drop('white')

ball  pencil
red       3       5
green     6       8

# Removing Duplicates

In [31]:
dframe=pd.DataFrame({'colors':['white','white','red','red','white'],'value':[2,1,3,3,2]})

In [32]:
dframe

colors  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [33]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [34]:
dframe[dframe.duplicated()]

colors  value
3    red      3
4  white      2

In [38]:
dframe[dframe.drop_duplicates()]

ValueError: Boolean array expected for the condition, not object

# Mapping

# Replacing Values via Mapping

In [40]:
frame3=pd.DataFrame({'item':['ball','mug','pen','pencil','bat'],'colors':['white','rosso','verde','blue','yellow'],'price':[1,2,3,4,5]})

In [41]:
frame3

item  colors  price
0    ball   white      1
1     mug   rosso      2
2     pen   verde      3
3  pencil    blue      4
4     bat  yellow      5

In [43]:
newcolors={'rosso':'red','verde':'green'}

In [44]:
newcolors

{'rosso': 'red', 'verde': 'green'}

In [45]:
frame3.replace(newcolors)

item  colors  price
0    ball   white      1
1     mug     red      2
2     pen   green      3
3  pencil    blue      4
4     bat  yellow      5

In [47]:
ser=pd.Series([np.NaN,1,4,np.NaN,8])

In [48]:
ser

0    NaN
1    1.0
2    4.0
3    NaN
4    8.0
dtype: float64

In [49]:
ser.replace(np.NaN,0)

0    0.0
1    1.0
2    4.0
3    0.0
4    8.0
dtype: float64

# Adding Values via Mapping

In [50]:
frame4=pd.DataFrame({'friends':['zaber','sohag','shourob','harun'],'junior':['mamun','poritosh','nayeem','arif']})

In [51]:
frame4

friends    junior
0    zaber     mamun
1    sohag  poritosh
2  shourob    nayeem
3    harun      arif

In [54]:
seniors={'mamun':'dip','poritosh':'nasib','nayeem':'sojol','arif':'habib'}

In [55]:
seniors

{'mamun': 'dip', 'poritosh': 'nasib', 'nayeem': 'sojol', 'arif': 'habib'}

In [56]:
frame4['seniors']=frame4['junior'].map(seniors)

In [57]:
frame4

friends    junior seniors
0    zaber     mamun     dip
1    sohag  poritosh   nasib
2  shourob    nayeem   sojol
3    harun      arif   habib

# Rename the Indexes of the Axes

In [58]:
frame4

friends    junior seniors
0    zaber     mamun     dip
1    sohag  poritosh   nasib
2  shourob    nayeem   sojol
3    harun      arif   habib

In [59]:
reindex={0:'zero',1:'one',2:'two',3:'three'}

In [60]:
reindex

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

In [61]:
frame4.rename(reindex)

friends    junior seniors
zero     zaber     mamun     dip
one      sohag  poritosh   nasib
two    shourob    nayeem   sojol
three    harun      arif   habib

In [62]:
recolumn={'friends':'best friends','seniors':'best seniors'}

In [63]:
recolumn

{'friends': 'best friends', 'seniors': 'best seniors'}

In [65]:
frame4.rename(columns=recolumn)

best friends    junior best seniors
0        zaber     mamun          dip
1        sohag  poritosh        nasib
2      shourob    nayeem        sojol
3        harun      arif        habib

In [66]:
frame4.rename(columns={'junior':'colse juniors'})

friends colse juniors seniors
0    zaber         mamun     dip
1    sohag      poritosh   nasib
2  shourob        nayeem   sojol
3    harun          arif   habib

# Discretization and Binning

In [67]:
result= [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]

In [69]:
result

[12, 34, 67, 55, 28, 90, 99, 12, 3, 56, 74, 44, 87, 23, 49, 89, 87]

In [70]:
bins=[0,25,50,75,100]

In [72]:
cat = pd.cut(result,bins)

In [73]:
cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [74]:
cat.levels

AttributeError: 'Categorical' object has no attribute 'levels'

In [75]:
 cat.levels

AttributeError: 'Categorical' object has no attribute 'levels'

In [78]:
 cat.labels

AttributeError: module 'pandas' has no attribute 'cat'

In [77]:
pd.value_count(cat)

AttributeError: module 'pandas' has no attribute 'value_count'

# Detecting and Filtering Outliers

In [89]:
randframe=pd.DataFrame(np.random.rand(1000,3))

In [90]:
randframe

0         1         2
0    0.996810  0.471573  0.390601
1    0.934857  0.212461  0.416386
2    0.213382  0.969107  0.354166
3    0.454313  0.474221  0.401087
4    0.570993  0.462248  0.667855
..        ...       ...       ...
995  0.635364  0.750183  0.492876
996  0.016351  0.513246  0.846459
997  0.080399  0.939185  0.385753
998  0.787518  0.110702  0.359611
999  0.060457  0.382369  0.040518

[1000 rows x 3 columns]

In [91]:
randframe.describe()

0            1            2
count  1000.000000  1000.000000  1000.000000
mean      0.502155     0.505269     0.507990
std       0.286428     0.291525     0.291930
min       0.000974     0.001110     0.000614
25%       0.258524     0.248366     0.254629
50%       0.499136     0.515896     0.503857
75%       0.744564     0.761272     0.764593
max       0.999634     0.999940     0.998092

In [92]:
randframe.std()

0    0.286428
1    0.291525
2    0.291930
dtype: float64

In [97]:
randframe[(np.abs(randframe) > (3*randframe.std())).any(1)]

0         1         2
0    0.996810  0.471573  0.390601
1    0.934857  0.212461  0.416386
2    0.213382  0.969107  0.354166
7    0.753696  0.908458  0.379575
8    0.886727  0.896984  0.103005
..        ...       ...       ...
987  0.140176  0.170801  0.988483
988  0.132824  0.885457  0.024625
991  0.000974  0.461861  0.961137
993  0.734960  0.878677  0.084644
997  0.080399  0.939185  0.385753

[343 rows x 3 columns]

# Permutation

In [99]:
nframe=pd.DataFrame(np.arange(25).reshape(5,5))

In [100]:
nframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [104]:
new_order=np.random.permutation(5)

In [105]:
new_order

array([2, 3, 4, 1, 0])

In [106]:
nframe.take(new_order)

0   1   2   3   4
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
1   5   6   7   8   9
0   0   1   2   3   4

# Random Sampling

In [107]:
sample=np.random.randint(0,len(nframe),size=3)

In [108]:
sample

array([0, 1, 3])

In [109]:
nframe.take(sample)

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
3  15  16  17  18  19

# regular expression

In [110]:
import re

In [111]:
 text = "This is an\t odd \n text!"

In [112]:
re.split('\s+', text)

['This', 'is', 'an', 'odd', 'text!']

In [113]:
re.findall(text)

TypeError: findall() missing 1 required positional argument: 'string'

# Data aggreegation

In [3]:
frame=pd.DataFrame({ 'color': ['white','red','green','red','green'],'object': ['pen','pencil','pencil','ashtray','pen'],'price1' : [5.56,4.20,1.30,0.56,2.75],'price2' : [4.75,4.12,1.60,0.75,3.15]})

In [4]:
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [6]:
group=frame['price1'].groupby(frame['object'])

In [7]:
group

In [8]:
group.groups

{'ashtray': Int64Index([3], dtype='int64'),
 'pen': Int64Index([0, 4], dtype='int64'),
 'pencil': Int64Index([1, 2], dtype='int64')}

In [9]:
group.sum()

object
ashtray    0.56
pen        8.31
pencil     5.50
Name: price1, dtype: float64

In [10]:
group.mean()

object
ashtray    0.560
pen        4.155
pencil     2.750
Name: price1, dtype: float64

# Hierarchical Grouping

In [14]:
hgroup=frame['price2'].groupby([frame['color'],frame['object']])

In [13]:
 ggroup = frame['price1'].groupby([frame['color'],frame['object']])


In [15]:
hgroup

In [17]:
hgroup.groups

{('green', 'pen'): Int64Index([4], dtype='int64'),
 ('green', 'pencil'): Int64Index([2], dtype='int64'),
 ('red', 'ashtray'): Int64Index([3], dtype='int64'),
 ('red', 'pencil'): Int64Index([1], dtype='int64'),
 ('white', 'pen'): Int64Index([0], dtype='int64')}

In [18]:
hgroup.sum()

color  object 
green  pen        3.15
       pencil     1.60
red    ashtray    0.75
       pencil     4.12
white  pen        4.75
Name: price2, dtype: float64

In [19]:
hgroup.mean()

color  object 
green  pen        3.15
       pencil     1.60
red    ashtray    0.75
       pencil     4.12
white  pen        4.75
Name: price2, dtype: float64

In [20]:
hgroup1=frame[['price1','price2']].groupby(frame['color'])

In [21]:
hgroup1

In [22]:
hgroup1.mean()

price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [27]:
for name,group2 in frame.groupby('color'):
    print(name)
    print(group2)

green
   color  object  price1  price2
2  green  pencil    1.30    1.60
4  green     pen    2.75    3.15
red
  color   object  price1  price2
1   red   pencil    4.20    4.12
3   red  ashtray    0.56    0.75
white
   color object  price1  price2
0  white    pen    5.56    4.75


# Chain of Transformations

In [28]:
result1=frame['price1'].groupby(frame['color']).mean()

In [30]:
result1

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [31]:
type(result1)

pandas.core.series.Series

In [32]:
result2=frame.groupby(frame['color']).mean()

In [33]:
result2

price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [34]:
type(result2)

pandas.core.frame.DataFrame