# imporing pandas


In [1]:
import pandas as pd

# declareing series


In [3]:
s =pd.Series([1,2,3,4,5])

In [4]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

# declaring indexes value

In [5]:
s=pd.Series([1,2,3,4,5,6],index =['a','b','c','d','e','f'])

In [6]:
s

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

# To see the array value

In [8]:
s.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

# To see the array index

In [9]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

# selecting the internal elements

In [10]:
s[0]

1

In [11]:
s[3]

4

# slicing

In [12]:
s[0:3]

a    1
b    2
c    3
dtype: int64

In [13]:
s[3:]

d    4
e    5
f    6
dtype: int64

# Accessing with index name

In [14]:
s['c']

3

In [16]:
s[['a','b']]

a    1
b    2
dtype: int64

# Assign a new value to the seies

In [18]:
s[3] = 11

In [19]:
s['f'] = 12

In [20]:
s

a     1
b     2
c     3
d    11
e     5
f    12
dtype: int64

# Defining a series from numpy array

In [2]:
import numpy as np

In [24]:
arr = np.array(['one','two','three','four','five','six'])

In [25]:
arr

array(['one', 'two', 'three', 'four', 'five', 'six'], dtype='<U5')

In [29]:
se = pd.Series(arr,index=[1,2,3,4,5,6])

In [27]:
se

1      one
2      two
3    three
4     four
5     five
6      six
dtype: object

# Defining Series from other series

In [32]:
s1 =pd.Series(se)

In [33]:
s1

1      one
2      two
3    three
4     four
5     five
6      six
dtype: object

In [34]:
s

1      one
2      two
3    three
4     four
5     five
6      six
dtype: object

In [35]:
se

1      one
2      two
3    three
4     four
5     five
6      six
dtype: object

In [39]:
arr[2]=' three'

In [37]:
se

1      one
2      two
3    three
4     four
5     five
6      six
dtype: object

# Filtering value

In [40]:
se[se>'three']

2    two
dtype: object

In [41]:
s

1      one
2      two
3    three
4     four
5     five
6      six
dtype: object

In [42]:
s=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])


In [43]:
s

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

# Filter value which is less than 5

In [44]:
s[s<5]

a    1
b    2
c    3
d    4
dtype: int64

# Operations and Mathematical Functions

In [45]:
s/3

a    0.333333
b    0.666667
c    1.000000
d    1.333333
e    1.666667
f    2.000000
dtype: float64

In [46]:
s[1]/3

0.6666666666666666

# function referenced with np and the instance of the Series passed as argument

In [47]:
np.log(s)

a    0.000000
b    0.693147
c    1.098612
d    1.386294
e    1.609438
f    1.791759
dtype: float64

In [49]:
np.max(s)


6

In [50]:
np.min(s)


1

In [51]:
np.add(s[1],s[2])

5

# Evaluating value count and remove duplicate

In [52]:
serd =  pd.Series([1,0,2,1,2,3], index=['white','white','blue','green','green','yellow'])

In [53]:
serd

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

# to find all the value excluding duplicate
unique() function is used

In [54]:
serd.unique()

array([1, 0, 2, 3], dtype=int64)

# count the duplicate values 
value_counts() function is used

In [62]:
serd

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

In [82]:
serd.value_counts()

2    2
1    2
3    1
0    1
dtype: int64

# to check the value whether list contain or not 
isin() function is used

In [63]:
serd

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

In [60]:
serd.isin([2])

white     False
white     False
blue       True
green     False
green      True
yellow    False
dtype: bool

In [61]:
serd.isin([2,3])

white     False
white     False
blue       True
green     False
green      True
yellow     True
dtype: bool

# NaN Values

In [64]:
s2 = pd . Series([5,-3,np.NaN,14])

In [65]:
s2

0     5.0
1    -3.0
2     NaN
3    14.0
dtype: float64

# The isnull() and notnull() functions are very useful to identify the indexes without a value

In [66]:
s2.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [67]:
s2.notnull()

0     True
1     True
2    False
3     True
dtype: bool

# filtering using isnull() and notnull()

In [68]:
s2[s2.isnull()]

2   NaN
dtype: float64

In [69]:
s2[s2.notnull()]

0     5.0
1    -3.0
3    14.0
dtype: float64

# series as dictionary

In [71]:
mydict ={15:'abdullah',45:'shourb',57:'zaber',60:'shohag'}

In [72]:
s3 = pd.Series(mydict)

In [73]:
s3

15    abdullah
45      shourb
57       zaber
60      shohag
dtype: object

In [75]:
names = [15,16,17,45,57,60]
myseries = pd.Series(mydict,index=names)

In [76]:
myseries

15    abdullah
16         NaN
17         NaN
45      shourb
57       zaber
60      shohag
dtype: object

# Operations between Series

In [77]:
s+se


a    NaN
b    NaN
c    NaN
d    NaN
e    NaN
f    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
dtype: object

In [78]:
s3+myseries

15    abdullahabdullah
16                 NaN
17                 NaN
45        shourbshourb
57          zaberzaber
60        shohagshohag
dtype: object

# DataFrame

In [85]:
colors = pd.Series(['red','blue','yelow','green'])
object_c = pd.Series(['ball','pen','pencil','cat'])

# Defining a DataFrame

In [90]:
dataframe = pd.DataFrame({'colors':colors,'object':object})

In [91]:
dataframe

colors  object
0    red    ball
1   blue     pen
2  yelow  pencil
3  green     cat

In [93]:
friends={'id':[15,45,57,60],'name':['abdullah','shouorb','zaber','shohag']}

In [94]:
friends

{'id': [15, 45, 57, 60], 'name': ['abdullah', 'shouorb', 'zaber', 'shohag']}

In [95]:
data = pd.DataFrame(friends)

In [96]:
data

id      name
0  15  abdullah
1  45   shouorb
2  57     zaber
3  60    shohag

In [7]:
import pandas as pd

In [5]:
fruits = pd.Series(['apple','banana','cucumber','date'])

In [6]:
fruits

0       apple
1      banana
2    cucumber
3        date
dtype: object

In [7]:
dollars = pd.Series([1,4,5,6])

In [8]:
dollars


0    1
1    4
2    5
3    6
dtype: int64

In [9]:
fruit_dollar_data_frame =pd.DataFrame({'Fruits':fruits,'dollars':dollars})

In [10]:
fruit_dollar_data_frame

Fruits  dollars
0     apple        1
1    banana        4
2  cucumber        5
3      date        6

# using index and columns in data frame

In [4]:
import numpy as np
frame1 = pd.DataFrame(np.arange(16).reshape((4,4)),index=['red','green','blue','yellow'],columns=['ball','cell','tool','kit'])

NameError: name 'pd' is not defined

In [47]:
frame1

ball  cell  tool  kit
red        0     1     2    3
green      4     5     6    7
blue       8     9    10   11
yellow    12    13    14   15

# Finding the name of columns and indexes names

In [22]:
frame1.index

Index(['red', 'green', 'blue', 'yellow'], dtype='object')

In [23]:
frame1.columns


Index(['ball', 'cell', 'tool', 'kit'], dtype='object')

In [24]:
frame1.values


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [2]:
ict={'id':[15,45,57,60],'name':['abdullah','shourb','zaber','sohag']}

In [8]:
data = pd.DataFrame({'id':[15,45,57,60],'name':['abdullah','shourb','zaber','sohag']})

In [9]:
data

id      name
0  15  abdullah
1  45    shourb
2  57     zaber
3  60     sohag

In [14]:
data.values

array([[15, 'abdullah'],
       [45, 'shourb'],
       [57, 'zaber'],
       [60, 'sohag']], dtype=object)

In [15]:
data['id']


0    15
1    45
2    57
3    60
Name: id, dtype: int64

In [17]:
data.ix[1]

AttributeError: 'DataFrame' object has no attribute 'ix'

In [18]:
data[1:]

id    name
1  45  shourb
2  57   zaber
3  60   sohag

In [20]:
data['CGPA'] =3.80

In [21]:
data

id      name  CGPA
0  15  abdullah   3.8
1  45    shourb   3.8
2  57     zaber   3.8
3  60     sohag   3.8

In [22]:
data[1]=3.3

In [23]:
data[2]=3.2

In [24]:
data[3]=3.4

In [25]:
data

id      name  CGPA    1    2    3
0  15  abdullah   3.8  3.3  3.2  3.4
1  45    shourb   3.8  3.3  3.2  3.4
2  57     zaber   3.8  3.3  3.2  3.4
3  60     sohag   3.8  3.3  3.2  3.4

In [26]:
data['CGPA'] = [3.5,3.4,3.3,3.45]

In [27]:
data

id      name  CGPA    1    2    3
0  15  abdullah  3.50  3.3  3.2  3.4
1  45    shourb  3.40  3.3  3.2  3.4
2  57     zaber  3.30  3.3  3.2  3.4
3  60     sohag  3.45  3.3  3.2  3.4

In [28]:
data['CGPA'][0]=3.8

C:\Users\ABDULLAH\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [29]:
data

id      name  CGPA    1    2    3
0  15  abdullah  3.80  3.3  3.2  3.4
1  45    shourb  3.40  3.3  3.2  3.4
2  57     zaber  3.30  3.3  3.2  3.4
3  60     sohag  3.45  3.3  3.2  3.4

In [30]:
data.isin([3.3,'CGPA'])

id   name   CGPA     1      2      3
0  False  False  False  True  False  False
1  False  False  False  True  False  False
2  False  False   True  True  False  False
3  False  False  False  True  False  False

In [31]:
data.isin([3.8])

id   name   CGPA      1      2      3
0  False  False   True  False  False  False
1  False  False  False  False  False  False
2  False  False  False  False  False  False
3  False  False  False  False  False  False

In [34]:
del data[1]

In [35]:
data

id      name  CGPA    2    3
0  15  abdullah  3.80  3.2  3.4
1  45    shourb  3.40  3.2  3.4
2  57     zaber  3.30  3.2  3.4
3  60     sohag  3.45  3.2  3.4

In [36]:
del data[2]

In [37]:
del data[3]

In [38]:
data

id      name  CGPA
0  15  abdullah  3.80
1  45    shourb  3.40
2  57     zaber  3.30
3  60     sohag  3.45

In [39]:
del data['CGPA']

In [40]:
data

id      name
0  15  abdullah
1  45    shourb
2  57     zaber
3  60     sohag

In [43]:
data[data<20]

TypeError: '<' not supported between instances of 'str' and 'int'

In [50]:
frame1[frame1<12]

ball  cell  tool   kit
red      0.0   1.0   2.0   3.0
green    4.0   5.0   6.0   7.0
blue     8.0   9.0  10.0  11.0
yellow   NaN   NaN   NaN   NaN

In [51]:
nestdict ={'red':{2012:23,2015:18},'green':{2012:16,2015:15,2018:20},'Blue':{2012:6,2015:8}}

In [54]:
nestData =pd.DataFrame(nestdict)

In [55]:
nestData

red  green  Blue
2012  23.0     16   6.0
2015  18.0     15   8.0
2018   NaN     20   NaN

In [56]:
data.T

0       1      2      3
id          15      45     57     60
name  abdullah  shourb  zaber  sohag

In [57]:
frame1.T

red  green  blue  yellow
ball    0      4     8      12
cell    1      5     9      13
tool    2      6    10      14
kit     3      7    11      15

# methods on index

In [59]:
data.idxmin()

TypeError: reduction operation 'argmin' not allowed for this dtype

In [60]:
s.idxmin()

0

In [61]:
s.idxmax()

4

In [62]:
serd = pd.Series(range(6),index=['white','white','red','green','blue','yellow'])

In [63]:
serd

white     0
white     1
red       2
green     3
blue      4
yellow    5
dtype: int64

In [64]:
serd['white']

white    0
white    1
dtype: int64

In [67]:
serd.index.is_unique

False

In [10]:
data

id      name
0  15  abdullah
1  45    shourb
2  57     zaber
3  60     sohag

# reindexing

In [ ]:
data.reindex([1,3,0,2])

In [41]:
data

id      name
0  15  abdullah
1  45    shourb
2  57     zaber
3  60     sohag

# Droping with index

In [14]:
data.drop(0)

id    name
1  45  shourb
2  57   zaber
3  60   sohag

# Droping with colums

In [17]:
data.drop(['id'],axis =1)

name
0  abdullah
1    shourb
2     zaber
3     sohag

In [ ]:

s1=pd.Series([3,2,5,1],['white','yellow','green','blue'])

In [19]:
s1

white     3
yellow    2
green     5
blue      1
dtype: int64

In [20]:
s2 = pd.Series([1,4,7,2,1],['white','yellow','black','blue','brown'])

In [21]:
s2

white     1
yellow    4
black     7
blue      2
brown     1
dtype: int64

In [22]:
s1+s2

black     NaN
blue      3.0
brown     NaN
green     NaN
white     4.0
yellow    6.0
dtype: float64

# Operation

In [19]:
frame1=pd.DataFrame(np.arange(16).reshape((4,4)),index =['red','blue','yellow','white'],columns = ['ball','pen','pencil','paper'])

In [20]:
frame1

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [37]:
frame2 = pd.DataFrame(np.arange(12).reshape((4,3)),index=['blue','green','white','yellow'],columns=['mug','pen','ball'])

In [33]:
frame2

mug  pen  ball
blue      0    1     2
green     3    4     5
white     6    7     8
yellow    9   10    11

In [39]:
frame1+frame2

ball  mug  paper   pen  pencil
blue     6.0  NaN    NaN   6.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   20.0  NaN    NaN  20.0     NaN
yellow  19.0  NaN    NaN  19.0     NaN

In [40]:
frame1

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

# Flexible Arithmetic Methods

In [42]:
frame1.add(frame2)

ball  mug  paper   pen  pencil
blue     6.0  NaN    NaN   6.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   20.0  NaN    NaN  20.0     NaN
yellow  19.0  NaN    NaN  19.0     NaN

In [43]:
frame1.div(frame2)

ball  mug  paper       pen  pencil
blue    2.000000  NaN    NaN  5.000000     NaN
green        NaN  NaN    NaN       NaN     NaN
red          NaN  NaN    NaN       NaN     NaN
white   1.500000  NaN    NaN  1.857143     NaN
yellow  0.727273  NaN    NaN  0.900000     NaN

In [44]:
frame1.sub(frame2)

ball  mug  paper  pen  pencil
blue     2.0  NaN    NaN  4.0     NaN
green    NaN  NaN    NaN  NaN     NaN
red      NaN  NaN    NaN  NaN     NaN
white    4.0  NaN    NaN  6.0     NaN
yellow  -3.0  NaN    NaN -1.0     NaN

# Function Application and Mapping

In [46]:
frame1.sqrt

AttributeError: 'DataFrame' object has no attribute 'sqrt'

In [47]:
np.sqrt(frame1)

ball       pen    pencil     paper
red     0.000000  1.000000  1.414214  1.732051
blue    2.000000  2.236068  2.449490  2.645751
yellow  2.828427  3.000000  3.162278  3.316625
white   3.464102  3.605551  3.741657  3.872983

# Functions by Row or Column

In [48]:
f = lambda x: x.min()-x.min()

In [49]:
frame1.apply(f)

ball      0
pen       0
pencil    0
paper     0
dtype: int64

In [50]:
def f(x):
    return x.max()-x.min()

In [51]:
frame2.apply(f)

mug     9
pen     9
ball    9
dtype: int64

In [52]:
frame1.apply(f,axis = 1)

red       3
blue      3
yellow    3
white     3
dtype: int64

# Statistics Functions

In [55]:
frame1

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [54]:
frame1.sum()

ball      24
pen       28
pencil    32
paper     36
dtype: int64

In [56]:
frame2

mug  pen  ball
blue      0    1     2
green     3    4     5
white     6    7     8
yellow    9   10    11

In [57]:
frame2.sum()

mug     18
pen     22
ball    26
dtype: int64

In [58]:
frame1.mean()

ball      6.0
pen       7.0
pencil    8.0
paper     9.0
dtype: float64

In [59]:
frame2.mean()

mug     4.5
pen     5.5
ball    6.5
dtype: float64

In [60]:
frame1.describe()

ball        pen     pencil      paper
count   4.000000   4.000000   4.000000   4.000000
mean    6.000000   7.000000   8.000000   9.000000
std     5.163978   5.163978   5.163978   5.163978
min     0.000000   1.000000   2.000000   3.000000
25%     3.000000   4.000000   5.000000   6.000000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000

In [62]:
frame2.describe()

mug        pen       ball
count  4.000000   4.000000   4.000000
mean   4.500000   5.500000   6.500000
std    3.872983   3.872983   3.872983
min    0.000000   1.000000   2.000000
25%    2.250000   3.250000   4.250000
50%    4.500000   5.500000   6.500000
75%    6.750000   7.750000   8.750000
max    9.000000  10.000000  11.000000

In [63]:
 ser = pd.Series([5,0,3,8,4], index=['red','blue','yellow','white','green'])

In [65]:
ser

red       5
blue      0
yellow    3
white     8
green     4
dtype: int64

In [66]:
ser.sort_index()

blue      0
green     4
red       5
white     8
yellow    3
dtype: int64

In [67]:
ser.sort_index(ascending=False)

yellow    3
white     8
red       5
green     4
blue      0
dtype: int64

In [68]:
frame1

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [69]:
frame1.sort_index()

ball  pen  pencil  paper
blue       4    5       6      7
red        0    1       2      3
white     12   13      14     15
yellow     8    9      10     11

In [70]:
frame1.sort_index(ascending = False)

ball  pen  pencil  paper
yellow     8    9      10     11
white     12   13      14     15
red        0    1       2      3
blue       4    5       6      7

In [71]:
frame2

mug  pen  ball
blue      0    1     2
green     3    4     5
white     6    7     8
yellow    9   10    11

In [72]:
frame2.sort_index()

mug  pen  ball
blue      0    1     2
green     3    4     5
white     6    7     8
yellow    9   10    11

In [73]:
frame2.sort_index(ascending = False)

mug  pen  ball
yellow    9   10    11
white     6    7     8
green     3    4     5
blue      0    1     2

In [74]:
frame1.sort_index(by = 'ball')

TypeError: sort_index() got an unexpected keyword argument 'by'

In [75]:
 frame1.sort_index(by='pen')

TypeError: sort_index() got an unexpected keyword argument 'by'

In [76]:
frame1.order()

AttributeError: 'DataFrame' object has no attribute 'order'

In [77]:
ser.order()

AttributeError: 'Series' object has no attribute 'order'

In [78]:
ser.order()

AttributeError: 'Series' object has no attribute 'order'

In [79]:
ser.rank()

red       4.0
blue      1.0
yellow    2.0
white     5.0
green     3.0
dtype: float64

# Correlation and Covariance

In [81]:
 seq2 = pd.Series([3,4,3,4,5,4,3,2],['2006','2007','2008','2009','2010','2011','2012','2013'])

In [82]:
seq2

2006    3
2007    4
2008    3
2009    4
2010    5
2011    4
2012    3
2013    2
dtype: int64

In [84]:
 seq = pd.Series([1,2,3,4,4,3,2,1],['2006','2007','2008','2009','2010','2011','2012','2013'])

In [85]:
seq

2006    1
2007    2
2008    3
2009    4
2010    4
2011    3
2012    2
2013    1
dtype: int64

In [86]:
seq2.cov(seq)

0.8571428571428571

In [87]:
seq2.corr(seq)

0.7745966692414834

In [88]:
seq.corr(seq2)

0.7745966692414835

In [89]:
seq.cov(seq2)

0.8571428571428571

In [90]:
frame1

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [91]:
frame2

mug  pen  ball
blue      0    1     2
green     3    4     5
white     6    7     8
yellow    9   10    11

In [92]:
frame1.cov()

ball        pen     pencil      paper
ball    26.666667  26.666667  26.666667  26.666667
pen     26.666667  26.666667  26.666667  26.666667
pencil  26.666667  26.666667  26.666667  26.666667
paper   26.666667  26.666667  26.666667  26.666667

In [93]:
frame1.corr()

ball  pen  pencil  paper
ball     1.0  1.0     1.0    1.0
pen      1.0  1.0     1.0    1.0
pencil   1.0  1.0     1.0    1.0
paper    1.0  1.0     1.0    1.0

In [94]:
frame1.corrwith(frame2)

ball      0.654654
pen       0.654654
mug            NaN
paper          NaN
pencil         NaN
dtype: float64

# Assigning a NaN Value

In [98]:
series = pd.Series([0,1,2,3,np.NaN,5],['a','b','c','d','e','f'])

In [96]:
series

a    0.0
b    1.0
c    2.0
d    3.0
e    NaN
f    5.0
dtype: float64

# Filtering Out NaN Values

In [99]:
series.dropna()

a    0.0
b    1.0
c    2.0
d    3.0
f    5.0
dtype: float64

In [100]:
series[series.notnull()]

a    0.0
b    1.0
c    2.0
d    3.0
f    5.0
dtype: float64

In [101]:
series[series.isnull()]

e   NaN
dtype: float64

In [102]:
frame = pd.DataFrame([6,np.NaN,6],[np.nan,np.nan,np.nan],[2,np.nan,5],index = ['blue','green','red'],columns =['ball','mug','pen'])

TypeError: __init__() got multiple values for argument 'index'

# Hierarchical Indexing and Leveling

In [6]:
mser =pd.Series(np.random.rand(8),index=[['white','white','white','blue','blue','red','red','red'],['up','down','right','up','down','up', 'down','left']])

In [7]:
mser

white  up       0.705032
       down     0.156094
       right    0.176666
blue   up       0.530909
       down     0.749786
red    up       0.438795
       down     0.944683
       left     0.185747
dtype: float64

In [8]:
mser.index

MultiIndex([('white',    'up'),
            ('white',  'down'),
            ('white', 'right'),
            ( 'blue',    'up'),
            ( 'blue',  'down'),
            (  'red',    'up'),
            (  'red',  'down'),
            (  'red',  'left')],
           )

In [11]:
mser.values

array([0.70503172, 0.15609433, 0.17666605, 0.53090897, 0.74978617,
       0.43879456, 0.94468328, 0.18574703])

In [12]:
mser['white']

up       0.705032
down     0.156094
right    0.176666
dtype: float64

In [14]:
mser[:,'up']

white    0.705032
blue     0.530909
red      0.438795
dtype: float64

In [15]:
mser['white','right']

0.17666604500301408

#  unstack() function

In [16]:
mser.unstack()

down      left     right        up
blue   0.749786       NaN       NaN  0.530909
red    0.944683  0.185747       NaN  0.438795
white  0.156094       NaN  0.176666  0.705032

In [18]:
frame1

NameError: name 'frame1' is not defined

In [21]:
frame1

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [22]:
frame1.stack()

red     ball       0
        pen        1
        pencil     2
        paper      3
blue    ball       4
        pen        5
        pencil     6
        paper      7
yellow  ball       8
        pen        9
        pencil    10
        paper     11
white   ball      12
        pen       13
        pencil    14
        paper     15
dtype: int32

In [23]:
frame1.unstack()

ball    red        0
        blue       4
        yellow     8
        white     12
pen     red        1
        blue       5
        yellow     9
        white     13
pencil  red        2
        blue       6
        yellow    10
        white     14
paper   red        3
        blue       7
        yellow    11
        white     15
dtype: int32

In [26]:
mframe = pd.DataFrame(np.random.rand(16).reshape(4,4),index = [['white','white','red','red'],['up','down','up','down']],columns =[['pen','pen','paper','paper'],[1,2,1,2]])

In [27]:
mframe

pen               paper          
                   1         2         1         2
white up    0.800844  0.382995  0.204255  0.168497
      down  0.894172  0.882369  0.438605  0.590005
red   up    0.857879  0.484917  0.662264  0.104871
      down  0.930129  0.770196  0.684736  0.776464

In [28]:
mframe.unstack()

pen                                   paper                      \
              1                   2                   1                   2   
           down        up      down        up      down        up      down   
red    0.930129  0.857879  0.770196  0.484917  0.684736  0.662264  0.776464   
white  0.894172  0.800844  0.882369  0.382995  0.438605  0.204255  0.590005   

                 
                 
             up  
red    0.104871  
white  0.168497

# Reordering and Sorting Levels

In [29]:
mframe.columns.names = ['onjects','id']

In [30]:
mframe.index.names = ['colors','status']

In [32]:
mframe

onjects             pen               paper          
id                    1         2         1         2
colors status                                        
white  up      0.800844  0.382995  0.204255  0.168497
       down    0.894172  0.882369  0.438605  0.590005
red    up      0.857879  0.484917  0.662264  0.104871
       down    0.930129  0.770196  0.684736  0.776464

In [33]:
mframe.swaplevel('colors','status')

onjects             pen               paper          
id                    1         2         1         2
status colors                                        
up     white   0.800844  0.382995  0.204255  0.168497
down   white   0.894172  0.882369  0.438605  0.590005
up     red     0.857879  0.484917  0.662264  0.104871
down   red     0.930129  0.770196  0.684736  0.776464