# Introduction to numpy

In [6]:
# importing numpy
import numpy as np
np.__version__

'1.19.2'

In [7]:
# np.<tab>
np.abs

<ufunc 'absolute'>

In [8]:
np?

### Creating an array using array() function

In [10]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [11]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Find the type of the creating array using type() function

In [13]:
type(a2)

numpy.ndarray

In [14]:
type(arr)

numpy.ndarray

### Find the dtype of the array using 'dtype' attribute

In [19]:
arr

array([1, 2, 3, 4])

In [15]:
arr.dtype

dtype('int32')

In [20]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
a2.dtype

dtype('int32')

In [37]:
af=np.array([0.2,0.3,0.4])
af

array([0.2, 0.3, 0.4])

In [38]:
af.dtype

dtype('float64')

In [39]:
ac=np.array([1+2j,3+4j])
ac

array([1.+2.j, 3.+4.j])

In [40]:
ac.dtype

dtype('complex128')

### Finding the dimension using 'ndim'

In [18]:
arr

array([1, 2, 3, 4])

In [21]:
arr.ndim

1

In [22]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
a2.ndim

2

In [25]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [26]:
a3.ndim

3

### Finding the array length using 'size'attributes

In [28]:
arr

array([1, 2, 3, 4])

In [29]:
arr.size

4

In [30]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
a2.size

10

In [32]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [33]:
a3.size

9

### Finding the shape using 'shape' attribute 

In [41]:
arr

array([1, 2, 3, 4])

In [42]:
arr.shape

(4,)

In [43]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
a2.shape

(2, 5)

In [45]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [46]:
a3.shape

(1, 3, 3)

In [47]:
ac

array([1.+2.j, 3.+4.j])

In [48]:
ac.shape

(2,)

### Finding the size of array in bytes using 'itemsize' attributes

In [49]:
arr

array([1, 2, 3, 4])

In [50]:
arr.itemsize

4

In [51]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
a2.itemsize

4

In [53]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [54]:
a3.itemsize

4

### Creating an array using array() function with dtype options

In [60]:
ad=np.array([[7,8,9,2],[1,5,3,4]],dtype=complex)
ad

array([[7.+0.j, 8.+0.j, 9.+0.j, 2.+0.j],
       [1.+0.j, 5.+0.j, 3.+0.j, 4.+0.j]])

In [61]:
ad.ndim

2

In [62]:
ad.shape

(2, 4)

In [63]:
ad.size

8

In [64]:
ad.itemsize

16

In [65]:
ad.data

### Intrinsic creation of array using 'zeros()' and 'ones()' functions

In [69]:
a_0=np.zeros((3,3),dtype=float,order='F')
a_0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
a_1=np.ones((4,5),dtype=float,order='F')
a_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
a_1=np.ones((4,5),dtype=int,order='F')
a_1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Creating an array using arange() function.
arange([start,] stop[, step,], dtype=None)
* This function generates NumPy arrays with numerical sequences that
respond to particular rules depending on the passed arguments. For example, if you want to generate a
sequence of values between 0 and 10, you will be passed only one argument to the function, that is the value
with which you want to end the sequence.

In [73]:
arange=np.arange(0,10)
arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
ar1=np.arange(0,10,2)
ar1

array([0, 2, 4, 6, 8])

In [75]:
ar2=np.arange(10,100,11)
ar2

array([10, 21, 32, 43, 54, 65, 76, 87, 98])

### Generate two dimensional array with reshape() function
arange(0,4).reshape(2,2)

In [81]:
are=np.arange(0,4)
are

array([0, 1, 2, 3])

In [83]:
are.ndim

1

In [84]:
are.shape

(4,)

In [85]:
are.size

4

In [77]:
are=np.arange(0,4).reshape(2,2)
are

array([[0, 1],
       [2, 3]])

In [78]:
are.ndim

2

In [79]:
are.shape

(2, 2)

### Creating an array using linspace() function.
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
This function still takes as its first two
arguments the initial and end values of the sequence, but the third argument, instead of specifying the
distance between one element and the next, defines the number of elements into which we want the interval
to be split.

In [86]:
al=np.linspace(0,10,9)
al

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [87]:
al1=np.linspace(0,5,100)

In [88]:
al1

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [90]:
al.reshape(3,3)

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

### Creating an array using 'np.random.random()' module


In [92]:
aran=np.random.random(3)
aran

array([0.83887248, 0.00310371, 0.17287244])

In [93]:
aran1=np.random.random((3,3))

In [94]:
aran1

array([[0.76750805, 0.50779111, 0.34303617],
       [0.2776071 , 0.36995732, 0.51542698],
       [0.2492301 , 0.68311986, 0.62978584]])

### Create a 3x3 array of normally distributed random values
with mean 0 and standard deviation 1

In [95]:
arn=np.random.normal(0,1,(3,3))
arn

array([[ 0.99965434, -0.7422205 ,  1.67518272],
       [-1.08196677,  0.29362122,  0.75905083],
       [ 0.66390875,  0.69446457,  0.9752152 ]])

In [96]:
arn1=np.random.normal(2,0.5,(3,3))

In [97]:
arn1

array([[1.93333287, 1.65038531, 2.29005691],
       [1.95340665, 1.25658349, 3.35453626],
       [2.15122467, 1.94423136, 1.08083089]])

### Create a 3x3 array of random integers in the interval [0, 10) using randint() function.


In [98]:
arandint=np.random.randint(0,10,(3,3))
arandint

array([[7, 2, 9],
       [0, 4, 1],
       [1, 7, 0]])

### Create a 3x3 identity matrix using 'eye()' function
np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

In [101]:
aiden=np.eye(3,3)
aiden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
iden=np.eye(4,4)
iden

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Create a 3x5 array filled with 3.14 using 'np.full()' function


In [106]:
afull=np.full((4,5),3.14)
afull

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [107]:
afull1=np.full((10,10),10)
afull1

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

### Create an uninitialized array of three integers.
The values will be whatever happens to already exist at that memory location
using 'np.empty()' function

In [108]:
aempty=np.empty(3)

In [109]:
aempty

array([1., 1., 1.])

## Indexing, Slicing, and Iterating

### 1.Indexing
Array indexing always refers to the use of square brackets (‘[ ]’) to index the elements of the array so that
it can then be referred individually for various uses such as extracting a value, selecting items, or even
assigning a new value.

In [110]:
arr

array([1, 2, 3, 4])

In [111]:
arr[3]

4

In [114]:
arr[-3]

2

In [115]:
arr[-1]

4

In [112]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### indexing two dimensional arrays
In a multidimensional array, you access items using a comma-separated tuple of
indices

a2[1,2]

In [127]:
a2[1,2]

8

In [122]:
a2[0,2]

3

In [123]:
a3[0,0]

array([1, 2, 3])

In [125]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [126]:
a2[0,0]

1

### Modify values of any array using index notation

In [128]:
# Modifying one dimensional array
arr

array([1, 2, 3, 4])

In [129]:
arr[1]=0
arr

array([1, 0, 3, 4])

In [130]:
# Modifying two dimensional array
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [132]:
a2[1,0]=0
a2

array([[ 1,  2,  3,  4,  5],
       [ 0,  7,  8,  9, 10]])

### Fancy indexing
Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [325]:
arr=np.empty((8,4))

In [327]:
for i in range(8):
    arr[i]=i

In [328]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [329]:
arr[[2,3,4]]

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [330]:
arr[[-5,-6]]

array([[3., 3., 3., 3.],
       [2., 2., 2., 2.]])

In [332]:
 arr = np.arange(32).reshape((8, 4))

In [333]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [334]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

### 1.2 Slicing
Slicing is the operation which allows you to extract portions of an array to generate new ones. Whereas using the Python lists the arrays obtained by slicing are copies, in NumPy, arrays are views onto the same underlying buffer

### 1.2.1-dimensional array slicing

In [155]:
arr

array([1, 0, 3, 4])

In [144]:
# Elements from index 1 to 3(exlcude)
arr[1:3]

array([0, 3])

In [145]:
# First 3 elements
arr[:3]

array([1, 0, 3])

In [146]:
# Element after index 3
arr[3:]

array([4])

In [136]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 0,  7,  8,  9, 10]])

In [148]:
# Every other eleements
arr[::2]

array([1, 3])

In [149]:
# Every other elements
arr[2::]

array([3, 4])

In [150]:
arr[-1]

4

In [152]:
arr[3::-1]

array([4, 3, 0, 1])

### 1.2.2 Multidimensional array slicing

In [157]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 0,  7,  8,  9, 10]])

In [164]:
# 2 rows ,columns 3
a2[:2,:3]

array([[1, 2, 3],
       [0, 7, 8]])

In [159]:
x2=np.array([[12, 5, 2, 4],
 [ 7, 6, 8, 8],
 [ 1, 6, 7, 7]])

In [160]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [161]:
x2[:1,:2]

array([[12,  5]])

In [165]:
# 1 rows
x2[:1]

array([[12,  5,  2,  4]])

In [169]:

x2[:2,::1]

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8]])

In [170]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [171]:
x2[0:2,0:2]

array([[12,  5],
       [ 7,  6]])

## 1.3 Iterating over arrays

In [173]:
arr

array([1, 0, 3, 4])

In [174]:
for i in arr:
    print(i)

1
0
3
4


In [175]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [176]:
for i in x2:
    print(i)

[12  5  2  4]
[7 6 8 8]
[1 6 7 7]


In [179]:
#If you want to make an iteration element by element you may use the following construct, using the for loop on x2.flat
for i in x2.flat:
    print(i)
    

12
5
2
4
7
6
8
8
1
6
7
7


### 1.3.1 Iterating using  the 'apply_along_axis()' function

In [183]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [182]:
np.apply_along_axis(np.mean,axis=0,arr=x2)

array([6.66666667, 5.66666667, 5.66666667, 6.33333333])

In [184]:
np.apply_along_axis(np.mean,axis=1,arr=x2)

array([5.75, 7.25, 5.25])

In [185]:
def square(x):
    return x*x

In [186]:
np.apply_along_axis(square,axis=1,arr=x2)

array([[144,  25,   4,  16],
       [ 49,  36,  64,  64],
       [  1,  36,  49,  49]])

## Basic Operations

### 1.1 Arithmetic operators

In [187]:
arr

array([1, 0, 3, 4])

In [188]:
arr+4

array([5, 4, 7, 8])

In [189]:
arr-4

array([-3, -4, -1,  0])

In [190]:
arr/4

array([0.25, 0.  , 0.75, 1.  ])

In [191]:
arr*4

array([ 4,  0, 12, 16])

In [192]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 0,  7,  8,  9, 10]])

In [193]:
a2/4

array([[0.25, 0.5 , 0.75, 1.  , 1.25],
       [0.  , 1.75, 2.  , 2.25, 2.5 ]])

In [194]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [195]:
a3*6

array([[[ 6, 12, 18],
        [24, 30, 36],
        [42, 48, 54]]])

In [196]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 0,  7,  8,  9, 10]])

In [197]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [203]:
a2=np.arange(0,12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [204]:
x2+a2

array([[12,  6,  4,  7],
       [11, 11, 14, 15],
       [ 9, 15, 17, 18]])

In [205]:
x2-a2

array([[12,  4,  0,  1],
       [ 3,  1,  2,  1],
       [-7, -3, -3, -4]])

In [206]:
np.add(arr,5)

array([6, 5, 8, 9])

In [207]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [208]:
np.subtract(x2,5)

array([[ 7,  0, -3, -1],
       [ 2,  1,  3,  3],
       [-4,  1,  2,  2]])

In [210]:
np.mod(x2,3)

array([[0, 2, 2, 1],
       [1, 0, 2, 2],
       [1, 0, 1, 1]], dtype=int32)

### 1.2 The Matrix Product
Using  dot() function.
* The result at each position is the sum of the products between each element of the corresponding
row of the first matrix with the corresponding element of the corresponding column of the second matrix. 

In [242]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [243]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [249]:
a2=a2.reshape(4,3)
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [250]:
np.dot(a2,x2)

array([[  9,  18,  22,  22],
       [ 69,  69,  73,  79],
       [129, 120, 124, 136],
       [189, 171, 175, 193]])

In [251]:
a2.dot(x2)

array([[  9,  18,  22,  22],
       [ 69,  69,  73,  79],
       [129, 120, 124, 136],
       [189, 171, 175, 193]])

In [252]:
x2.dot(a2)

array([[ 63,  86, 109],
       [138, 167, 196],
       [123, 144, 165]])

### 1.3 Increment and Decrement Operators

In [253]:
arr

array([1, 0, 3, 4])

In [254]:
arr +=1

In [255]:
arr

array([2, 1, 4, 5])

In [256]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [257]:
a2 -=1

In [258]:
a2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 1.4 Aggregate functions

In [259]:
arr

array([2, 1, 4, 5])

In [260]:
arr.mean()

3.0

In [261]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [262]:
x2.mean()

6.083333333333333

In [265]:
x2.std()

2.7826346428439996

In [274]:
arr

array([2, 1, 4, 5])

In [278]:
np.add.reduce(arr)

12

In [279]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [280]:
np.add.reduce(x2)

array([20, 17, 17, 19])

In [281]:
np.multiply.reduce(x2)

array([ 84, 180, 112, 224])

In [282]:
np.add.accumulate(arr)

array([ 2,  3,  7, 12], dtype=int32)

In [283]:
np.add.accumulate(x2)

array([[12,  5,  2,  4],
       [19, 11, 10, 12],
       [20, 17, 17, 19]], dtype=int32)

In [284]:
a2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [285]:
np.multiply.accumulate(a2)

array([[ -1,   0,   1],
       [ -2,   0,   4],
       [-10,   0,  28],
       [-80,   0, 280]], dtype=int32)

In [286]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [288]:
np.multiply.outer(x2,x2)

array([[[[144,  60,  24,  48],
         [ 84,  72,  96,  96],
         [ 12,  72,  84,  84]],

        [[ 60,  25,  10,  20],
         [ 35,  30,  40,  40],
         [  5,  30,  35,  35]],

        [[ 24,  10,   4,   8],
         [ 14,  12,  16,  16],
         [  2,  12,  14,  14]],

        [[ 48,  20,   8,  16],
         [ 28,  24,  32,  32],
         [  4,  24,  28,  28]]],


       [[[ 84,  35,  14,  28],
         [ 49,  42,  56,  56],
         [  7,  42,  49,  49]],

        [[ 72,  30,  12,  24],
         [ 42,  36,  48,  48],
         [  6,  36,  42,  42]],

        [[ 96,  40,  16,  32],
         [ 56,  48,  64,  64],
         [  8,  48,  56,  56]],

        [[ 96,  40,  16,  32],
         [ 56,  48,  64,  64],
         [  8,  48,  56,  56]]],


       [[[ 12,   5,   2,   4],
         [  7,   6,   8,   8],
         [  1,   6,   7,   7]],

        [[ 72,  30,  12,  24],
         [ 42,  36,  48,  48],
         [  6,  36,  42,  42]],

        [[ 84,  35,  14,  28],
         [ 49, 

In [289]:
np.sum(arr)

12

In [290]:
x2.sum()

73

In [291]:
a2.sum()

54

## Ufuncs of numpy
### 1.1Trigonometric functions

In [213]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [211]:
np.sin(x2)

array([[-0.53657292, -0.95892427,  0.90929743, -0.7568025 ],
       [ 0.6569866 , -0.2794155 ,  0.98935825,  0.98935825],
       [ 0.84147098, -0.2794155 ,  0.6569866 ,  0.6569866 ]])

In [214]:
arr

array([1, 0, 3, 4])

In [212]:
np.cos(arr)

array([ 0.54030231,  1.        , -0.9899925 , -0.65364362])

In [215]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [217]:
np.tan(a3)

array([[[ 1.55740772, -2.18503986, -0.14254654],
        [ 1.15782128, -3.38051501, -0.29100619],
        [ 0.87144798, -6.79971146, -0.45231566]]])

In [221]:
# Inverse Trigonometric functions
np.arccos(arr)

<ipython-input-221-988cf176e2ad>:2: RuntimeWarning: invalid value encountered in arccos
  np.arccos(arr)


array([0.        , 1.57079633,        nan,        nan])

In [222]:
np.arcsin(a2)

<ipython-input-222-83367a2ca3fb>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(a2)


array([[0.        , 1.57079633,        nan,        nan],
       [       nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan]])

### 1.2 Exponents and logarithms

In [223]:
arr

array([1, 0, 3, 4])

In [224]:
np.exp(arr)

array([ 2.71828183,  1.        , 20.08553692, 54.59815003])

In [225]:
np.power(arr,2)

array([ 1,  0,  9, 16], dtype=int32)

In [226]:
np.exp2(arr)

array([ 2.,  1.,  8., 16.])

In [227]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [228]:
np.log(x2)

array([[2.48490665, 1.60943791, 0.69314718, 1.38629436],
       [1.94591015, 1.79175947, 2.07944154, 2.07944154],
       [0.        , 1.79175947, 1.94591015, 1.94591015]])

In [230]:
np.log2(x2)

array([[3.5849625 , 2.32192809, 1.        , 2.        ],
       [2.80735492, 2.5849625 , 3.        , 3.        ],
       [0.        , 2.5849625 , 2.80735492, 2.80735492]])

In [231]:
np.log10(x2)

array([[1.07918125, 0.69897   , 0.30103   , 0.60205999],
       [0.84509804, 0.77815125, 0.90308999, 0.90308999],
       [0.        , 0.77815125, 0.84509804, 0.84509804]])

### 1.3 Specialized ufuncs

In [268]:
from scipy import special

In [269]:
arr

array([2, 1, 4, 5])

In [270]:
special.gamma(arr)

array([ 1.,  1.,  6., 24.])

In [272]:
special.beta(arr,2)

array([0.16666667, 0.5       , 0.05      , 0.03333333])

In [273]:
a2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 1.4 Other ufuncs

In [232]:
arr

array([1, 0, 3, 4])

In [233]:
np.max(arr)

4

In [234]:
np.min(arr)

0

In [236]:
np.square(arr)

array([ 1,  0,  9, 16], dtype=int32)

In [237]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [238]:
np.sqrt(x2)

array([[3.46410162, 2.23606798, 1.41421356, 2.        ],
       [2.64575131, 2.44948974, 2.82842712, 2.82842712],
       [1.        , 2.44948974, 2.64575131, 2.64575131]])

In [241]:
np.sign(x2) #Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Conditional and boolean arrays

In [292]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [293]:
x2<5

array([[False, False,  True,  True],
       [False, False, False, False],
       [ True, False, False, False]])

In [294]:
x2[x2>5]

array([12,  7,  6,  8,  8,  6,  7,  7])

In [295]:
x2[x2<6]

array([5, 2, 4, 1])

In [298]:
x2[x2<5]

array([2, 4, 1])

In [300]:
np.count_nonzero(x2<5) # how many values less than 6?

3

In [301]:
np.sum(x2<6) # how many values less than 6?

4

In [302]:
np.sum(x2<6,axis=1) # how many values less than 6 in each row?

array([3, 0, 1])

In [303]:
np.any(x2>8) # are there any values greater than 8?

True

In [304]:
np.any(x2<0) # are there any values less than zero?

False

In [305]:
np.all(x2>8)

False

In [309]:
x2[x2>8]

array([12])

In [314]:
bool(42) #In Python, all nonzero integers will evaluate as True

True

In [312]:
bool(0)

False

In [313]:
bool(42)& bool(0)

False

In [315]:
a2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [316]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [317]:
a2 or x2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [318]:
A=np.array([1,0,1,0,1],dtype=bool)
B=np.array([1,0,0,0,1],dtype=bool)

In [319]:
A

array([ True, False,  True, False,  True])

In [320]:
B

array([ True, False, False, False,  True])

In [322]:
A|B

array([ True, False,  True, False,  True])

In [323]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [324]:
(x2>8) & (x2<12)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### Transposing Arrays and Swapping Axes
Arrays have the transpose method and also
the special T attribute

In [335]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [336]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [337]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [338]:
x2.transpose()

array([[12,  7,  1],
       [ 5,  6,  6],
       [ 2,  8,  7],
       [ 4,  8,  7]])

In [339]:
a2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

## Array manipulation

## 1.1 sorting array

In [345]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [347]:
x2.sort()
x2

array([[ 2,  4,  5, 12],
       [ 6,  7,  8,  8],
       [ 1,  6,  7,  7]])

In [348]:
x2

array([[ 2,  4,  5, 12],
       [ 6,  7,  8,  8],
       [ 1,  6,  7,  7]])

In [349]:
a2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [350]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [351]:
al

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [354]:
arr=np.random.random(12).reshape(3,4)
arr

array([[0.33818603, 0.79288541, 0.86692915, 0.3867088 ],
       [0.36718364, 0.57578915, 0.57497725, 0.22618368],
       [0.42127322, 0.75061676, 0.79342198, 0.19806249]])

In [355]:
np.sort(arr)

array([[0.33818603, 0.3867088 , 0.79288541, 0.86692915],
       [0.22618368, 0.36718364, 0.57497725, 0.57578915],
       [0.19806249, 0.42127322, 0.75061676, 0.79342198]])

In [356]:
arr

array([[0.33818603, 0.79288541, 0.86692915, 0.3867088 ],
       [0.36718364, 0.57578915, 0.57497725, 0.22618368],
       [0.42127322, 0.75061676, 0.79342198, 0.19806249]])

In [357]:
arr.argsort() #argsort, which instead returns the indices of the sorted elements

array([[0, 3, 1, 2],
       [3, 0, 2, 1],
       [3, 0, 1, 2]], dtype=int64)

In [358]:
# Sorting along rows or columns
arr

array([[0.33818603, 0.79288541, 0.86692915, 0.3867088 ],
       [0.36718364, 0.57578915, 0.57497725, 0.22618368],
       [0.42127322, 0.75061676, 0.79342198, 0.19806249]])

In [360]:
np.sort(arr,axis=0)

array([[0.33818603, 0.57578915, 0.57497725, 0.19806249],
       [0.36718364, 0.75061676, 0.79342198, 0.22618368],
       [0.42127322, 0.79288541, 0.86692915, 0.3867088 ]])

In [361]:
np.sort(arr,axis=1)

array([[0.33818603, 0.3867088 , 0.79288541, 0.86692915],
       [0.22618368, 0.36718364, 0.57497725, 0.57578915],
       [0.19806249, 0.42127322, 0.75061676, 0.79342198]])

In [363]:
# Partial Sorts: Partitioning
np.partition(arr,1)

array([[0.33818603, 0.3867088 , 0.86692915, 0.79288541],
       [0.22618368, 0.36718364, 0.57497725, 0.57578915],
       [0.19806249, 0.42127322, 0.79342198, 0.75061676]])

In [364]:
a2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [369]:
np.partition(a2,2)

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 1.2 Joining Arrays
* vstack() function
* hstack() function
* row_stack() function
* column_stack() function

In [370]:
arr

array([[0.33818603, 0.79288541, 0.86692915, 0.3867088 ],
       [0.36718364, 0.57578915, 0.57497725, 0.22618368],
       [0.42127322, 0.75061676, 0.79342198, 0.19806249]])

In [371]:
a2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [372]:
x2

array([[ 2,  4,  5, 12],
       [ 6,  7,  8,  8],
       [ 1,  6,  7,  7]])

In [375]:
np.vstack((x2,arr))

array([[ 2.        ,  4.        ,  5.        , 12.        ],
       [ 6.        ,  7.        ,  8.        ,  8.        ],
       [ 1.        ,  6.        ,  7.        ,  7.        ],
       [ 0.33818603,  0.79288541,  0.86692915,  0.3867088 ],
       [ 0.36718364,  0.57578915,  0.57497725,  0.22618368],
       [ 0.42127322,  0.75061676,  0.79342198,  0.19806249]])

In [376]:
np.hstack((arr,x2))

array([[ 0.33818603,  0.79288541,  0.86692915,  0.3867088 ,  2.        ,
         4.        ,  5.        , 12.        ],
       [ 0.36718364,  0.57578915,  0.57497725,  0.22618368,  6.        ,
         7.        ,  8.        ,  8.        ],
       [ 0.42127322,  0.75061676,  0.79342198,  0.19806249,  1.        ,
         6.        ,  7.        ,  7.        ]])

In [378]:
np.row_stack((arr,x2))

array([[ 0.33818603,  0.79288541,  0.86692915,  0.3867088 ],
       [ 0.36718364,  0.57578915,  0.57497725,  0.22618368],
       [ 0.42127322,  0.75061676,  0.79342198,  0.19806249],
       [ 2.        ,  4.        ,  5.        , 12.        ],
       [ 6.        ,  7.        ,  8.        ,  8.        ],
       [ 1.        ,  6.        ,  7.        ,  7.        ]])

In [380]:
np.column_stack((arr,x2))

array([[ 0.33818603,  0.79288541,  0.86692915,  0.3867088 ,  2.        ,
         4.        ,  5.        , 12.        ],
       [ 0.36718364,  0.57578915,  0.57497725,  0.22618368,  6.        ,
         7.        ,  8.        ,  8.        ],
       [ 0.42127322,  0.75061676,  0.79342198,  0.19806249,  1.        ,
         6.        ,  7.        ,  7.        ]])