In [1]:
import numpy as np

# 1.1  1-dimensional array using array function
Find the following:
    * type of the array usin type() function
    * dtype of the array using .dtype
    * shape of the array using .shape
    * dimension of the array using .ndim
    * size of the array using the .size
    * itemsize in byte of the array .itemsize 
    * buffer containg the elements using .data 
    

In [2]:

a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
a.size

3

In [8]:
a.itemsize

4

In [9]:
a.data

# 1.2  2-dimensional array using array function
Find the following:
    * type of the array usin type() function
    * dtype of the array using .dtype
    * shape of the array using .shape
    * dimension of the array using .ndim
    * size of the array using the .size
    * itemsize in byte of the array .itemsize 
    * buffer containg the elements using .data
    

In [13]:
a2=np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
type(a2)

numpy.ndarray

In [15]:
a2.dtype

dtype('int32')

In [16]:
a2.size

8

In [17]:
a2.shape

(2, 4)

In [18]:
a2.ndim

2

In [19]:
a2.itemsize

4

In [20]:
a2.data


# Creating an array

## 2.1.Using array() function


In [32]:
# using list
arr_l=np.array([[1,2,3,4],[5,6,7,8]])
arr_l

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
# using tuple
arr_t=np.array(((9,4,5),(3,9,1)))
arr_t

array([[9, 4, 5],
       [3, 9, 1]])

In [30]:
# Using sequence of tuple and list
arr_l_t=np.array([[1,2,3],(4,5,6),(6,7,8)])
arr_l_t

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [34]:
# Finding the types of data
arr_l.dtype


dtype('int32')

In [35]:
# finding the names of data types
arr_t.dtype.name

'int32'

In [37]:
# Creating an array using dtype function
f=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

# 2.2 Intrinsic creation of an array


In [38]:
# using zeros() function
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
# using the ones() function
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# using a arange() function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [43]:
# arange function with intervals
np.arange(5,6,.17)

array([5.  , 5.17, 5.34, 5.51, 5.68, 5.85])

In [45]:
# Generate two dimensional arrays
ar1=np.arange(0,12).reshape(3,4)
ar1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
# using the linspace function
#This function still takes as its first two
#arguments the initial and end values of the sequence, but the third argument, instead of specifying the
#distance between one element and the next, defines the number of elements into which we want the interval
#to be split.
ar1=np.linspace(3,4,9)
ar1

array([3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ])

In [48]:
# Creating array using numpy random function
np.random.random(3)

array([0.40982848, 0.87471445, 0.43078388])

In [50]:
np.random.random((3,4))

array([[0.39587029, 0.32514274, 0.12779441, 0.22836247],
       [0.13036111, 0.25268975, 0.65226076, 0.06783493],
       [0.29641405, 0.78593116, 0.96224457, 0.79621576]])

# 3.Basic Operations

# 3.1 arithmetic operation

In [52]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [53]:
a+4

array([4, 5, 6, 7])

In [54]:
a*4

array([ 0,  4,  8, 12])

In [56]:
b=np.arange(4,8)
b

array([4, 5, 6, 7])

In [57]:
a+b

array([ 4,  6,  8, 10])

In [58]:
a-b

array([-4, -4, -4, -4])

In [59]:
a/b

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [60]:
a*b

array([ 0,  5, 12, 21])

In [62]:
a*np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [63]:
np.sqrt(b)

array([2.        , 2.23606798, 2.44948974, 2.64575131])

In [64]:
np.square(a)

array([0, 1, 4, 9], dtype=int32)

In [71]:
a1=np.arange(0,20).reshape(4,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [77]:
a2=np.ones((4,5))
a2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
a1*a2

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

## 3.2 The matrix product

In [87]:
A=np.arange(2,12).reshape(2,5)
A

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [91]:
B=np.random.random((5,2))
B

array([[0.7998989 , 0.86831679],
       [0.68835229, 0.47168479],
       [0.63412046, 0.67241019],
       [0.08190867, 0.05825378],
       [0.41611989, 0.91999467]])

In [92]:
# using the .dot() function
np.dot(A,B)

array([[ 9.10759923, 11.65256563],
       [22.20960031, 26.60586674]])

In [93]:
A.dot(B)

array([[ 9.10759923, 11.65256563],
       [22.20960031, 26.60586674]])

In [94]:
B.dot(A)

array([[ 7.67801534,  9.34623103, 11.01444672, 12.68266242, 14.35087811],
       [ 4.67849807,  5.83853514,  6.99857222,  8.15860929,  9.31864636],
       [ 5.97511228,  7.28164293,  8.58817359,  9.89470424, 11.2012349 ],
       [ 0.57159379,  0.71175624,  0.85191869,  0.99208114,  1.13224359],
       [ 7.27220249,  8.60831706,  9.94443162, 11.28054619, 12.61666075]])

## 3.3 Incerement and decrement

In [96]:
a

array([0, 1, 2, 3])

In [100]:
# Decrement operator
a -=1

In [101]:
a

array([-1,  0,  1,  2])

In [104]:
#Increment operator
a +=4

In [105]:
a

array([4, 5, 6, 7])

## 3.4 universal functions(ufunc)
sqrt(),log(),sin() etc

In [107]:
a

array([4, 5, 6, 7])

In [108]:
# sqrt()
np.sqrt(a)

array([2.        , 2.23606798, 2.44948974, 2.64575131])

In [109]:
A

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [110]:
np.sqrt(A)

array([[1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479]])

In [111]:
np.log(a)

array([1.38629436, 1.60943791, 1.79175947, 1.94591015])

In [112]:
np.log(A)

array([[0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [113]:
np.sin(B)

array([[0.71728565, 0.76324248],
       [0.63526553, 0.45438774],
       [0.59246919, 0.62287334],
       [0.08181712, 0.05822084],
       [0.40421451, 0.79559839]])

## 3.5 Aggregate Functions
sum(),min(),max(),mean(),std() etc.

In [114]:

a

array([4, 5, 6, 7])

In [115]:
a.sum()

22

In [116]:
A

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [117]:
A.sum()

65

In [118]:
a.min()

4

In [119]:
a.max()

7

In [120]:
A.min()

2

In [121]:
B

array([[0.7998989 , 0.86831679],
       [0.68835229, 0.47168479],
       [0.63412046, 0.67241019],
       [0.08190867, 0.05825378],
       [0.41611989, 0.91999467]])

In [122]:
B.min()

0.0582537770408319

In [123]:
B.max()

0.919994672258305

In [124]:
B.std()

0.2873361292424563

## 3.6 Indexing, Slicing, and Iterating

### 3.6.1 Indexing
Array indexing always refers to the use of square brackets (‘[ ]’) to index the elements of the array so that
it can then be referred individually for various uses such as extracting a value, selecting items, or even
assigning a new value.

In [125]:
a

array([4, 5, 6, 7])

In [126]:
a[1]

5

In [127]:
a[0]

4

In [128]:
A

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [129]:
A[1]

array([ 7,  8,  9, 10, 11])

In [130]:
A[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [131]:
A[0]

array([2, 3, 4, 5, 6])

In [132]:
A[-1]

array([ 7,  8,  9, 10, 11])

In [133]:
A[0,-1]

6

In [134]:
A[1,3]

10

In [135]:
B

array([[0.7998989 , 0.86831679],
       [0.68835229, 0.47168479],
       [0.63412046, 0.67241019],
       [0.08190867, 0.05825378],
       [0.41611989, 0.91999467]])

In [138]:
B[3,1]

0.0582537770408319

## 3.6.2 Slicing
Slicing is the operation which allows you to extract portions of an array to generate new ones

In [140]:
A

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [141]:
B

array([[0.7998989 , 0.86831679],
       [0.68835229, 0.47168479],
       [0.63412046, 0.67241019],
       [0.08190867, 0.05825378],
       [0.41611989, 0.91999467]])

In [142]:
B[:-1]

array([[0.7998989 , 0.86831679],
       [0.68835229, 0.47168479],
       [0.63412046, 0.67241019],
       [0.08190867, 0.05825378]])

In [144]:
B[-1:]

array([[0.41611989, 0.91999467]])

In [145]:
A[1:2]

array([[ 7,  8,  9, 10, 11]])

## 3.6.3 Iterating an Array
using for loop

In [149]:
a

array([4, 5, 6, 7])

In [147]:
for i in a:
    print(i)

4
5
6
7


In [148]:
A

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [150]:
for i in A:
    print(i)

[2 3 4 5 6]
[ 7  8  9 10 11]


In [152]:
# If you want to make an iteration element by element you may use the following construct, using the for
#loop on A.flat.
for i in A.flat:
    print(i)

2
3
4
5
6
7
8
9
10
11
